namespace HMS.Modules.Identity.Infrastructure.Seed;

using System;

internal static class PermissionSeedData
{
    public static object[] GetPermissions()
    {
        return new object[]
        {
            new
            {
                Id = Guid.Parse("db3b17d7-811d-422a-a221-bb65a5037676"),
                Module = "patient-management",
                Action = "view",
                Key = "patient-management.view",
                Label = "View",
                DisplayOrder = 1,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("bb83e3bc-a4c0-42a8-a15e-3603132d08b6"),
                Module = "patient-management",
                Action = "create",
                Key = "patient-management.create",
                Label = "Create",
                DisplayOrder = 1,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("50adeda0-6191-4777-9430-6c4b359eff9d"),
                Module = "patient-management",
                Action = "edit",
                Key = "patient-management.edit",
                Label = "Edit",
                DisplayOrder = 1,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("bdb7a1ff-cfa7-4475-927d-ab389b0a06a8"),
                Module = "patient-management",
                Action = "delete",
                Key = "patient-management.delete",
                Label = "Delete",
                DisplayOrder = 1,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("2be079ff-aa89-4c47-bbda-cc8778209472"),
                Module = "clinical-care",
                Action = "view",
                Key = "clinical-care.view",
                Label = "View",
                DisplayOrder = 2,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("e71663b9-79ae-40ad-bf94-b8f402898658"),
                Module = "clinical-care",
                Action = "create",
                Key = "clinical-care.create",
                Label = "Create",
                DisplayOrder = 2,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("21ff0f71-fae5-4a0b-a7f8-ff08be7ff7bc"),
                Module = "clinical-care",
                Action = "edit",
                Key = "clinical-care.edit",
                Label = "Edit",
                DisplayOrder = 2,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("466d8793-d6b3-4e44-a20b-6688faef4f9f"),
                Module = "clinical-care",
                Action = "delete",
                Key = "clinical-care.delete",
                Label = "Delete",
                DisplayOrder = 2,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("1ef728c0-3cd0-46cb-b4d8-fa12101a2509"),
                Module = "diagnostics",
                Action = "view",
                Key = "diagnostics.view",
                Label = "View",
                DisplayOrder = 3,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("d0ad8c77-4d81-4773-9155-7c217e0877e6"),
                Module = "diagnostics",
                Action = "create",
                Key = "diagnostics.create",
                Label = "Create",
                DisplayOrder = 3,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("8509d991-b281-4259-bdb2-89ed75ec2f0d"),
                Module = "diagnostics",
                Action = "edit",
                Key = "diagnostics.edit",
                Label = "Edit",
                DisplayOrder = 3,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("8273002e-4bf7-4a05-84e5-3680154420e4"),
                Module = "diagnostics",
                Action = "delete",
                Key = "diagnostics.delete",
                Label = "Delete",
                DisplayOrder = 3,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("fbeecdff-38a9-42b1-98f2-c477d4c1af31"),
                Module = "pharmacy",
                Action = "view",
                Key = "pharmacy.view",
                Label = "View",
                DisplayOrder = 4,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("1cfc6580-0e9c-4055-b7de-3e9efcfdc306"),
                Module = "pharmacy",
                Action = "create",
                Key = "pharmacy.create",
                Label = "Create",
                DisplayOrder = 4,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("ef1023c8-e81a-4354-8994-6808089c4d2c"),
                Module = "pharmacy",
                Action = "edit",
                Key = "pharmacy.edit",
                Label = "Edit",
                DisplayOrder = 4,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("7dfefecb-3b08-4652-91d6-cf6de25ce057"),
                Module = "pharmacy",
                Action = "delete",
                Key = "pharmacy.delete",
                Label = "Delete",
                DisplayOrder = 4,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("e40d8eaf-ed39-4f76-b6f9-055db294d653"),
                Module = "support-services",
                Action = "view",
                Key = "support-services.view",
                Label = "View",
                DisplayOrder = 5,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("27964465-0e51-4494-8330-49fc7e66b084"),
                Module = "support-services",
                Action = "create",
                Key = "support-services.create",
                Label = "Create",
                DisplayOrder = 5,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("f477dc55-4359-4489-9d4c-b59003284609"),
                Module = "support-services",
                Action = "edit",
                Key = "support-services.edit",
                Label = "Edit",
                DisplayOrder = 5,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("47f91d93-a7ef-4156-966f-756b4142ba52"),
                Module = "support-services",
                Action = "delete",
                Key = "support-services.delete",
                Label = "Delete",
                DisplayOrder = 5,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("8cb7e9d1-1c22-44b0-9874-3d21e61e0e59"),
                Module = "finance-billing",
                Action = "view",
                Key = "finance-billing.view",
                Label = "View",
                DisplayOrder = 6,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("93d8f89c-edef-4580-8e0d-4419a9b1e0f7"),
                Module = "finance-billing",
                Action = "create",
                Key = "finance-billing.create",
                Label = "Create",
                DisplayOrder = 6,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("2542c897-7242-4423-9547-f7accb795a66"),
                Module = "finance-billing",
                Action = "edit",
                Key = "finance-billing.edit",
                Label = "Edit",
                DisplayOrder = 6,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("3bd21acb-54fe-44a4-80db-7b7d79768114"),
                Module = "finance-billing",
                Action = "delete",
                Key = "finance-billing.delete",
                Label = "Delete",
                DisplayOrder = 6,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("844e1456-87a8-4dca-8469-bb19117c7cb4"),
                Module = "records-compliance",
                Action = "view",
                Key = "records-compliance.view",
                Label = "View",
                DisplayOrder = 7,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("e1f0e24d-bdb1-48f1-a37d-bdfda4055886"),
                Module = "records-compliance",
                Action = "create",
                Key = "records-compliance.create",
                Label = "Create",
                DisplayOrder = 7,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("734f5ff4-48cf-4c78-8614-0c017a38eec6"),
                Module = "records-compliance",
                Action = "edit",
                Key = "records-compliance.edit",
                Label = "Edit",
                DisplayOrder = 7,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("200db0f5-cb8b-4ec6-bb4a-e380744dc7be"),
                Module = "records-compliance",
                Action = "delete",
                Key = "records-compliance.delete",
                Label = "Delete",
                DisplayOrder = 7,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("7d114d49-dd3f-422e-b920-8f42c105595f"),
                Module = "workforce-admin",
                Action = "view",
                Key = "workforce-admin.view",
                Label = "View",
                DisplayOrder = 8,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("113bf692-b2a7-4d56-9a20-e196bbab0cb6"),
                Module = "workforce-admin",
                Action = "create",
                Key = "workforce-admin.create",
                Label = "Create",
                DisplayOrder = 8,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("d90b82d1-e86d-44ae-a85d-64c4eef8cbae"),
                Module = "workforce-admin",
                Action = "edit",
                Key = "workforce-admin.edit",
                Label = "Edit",
                DisplayOrder = 8,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("7e6ef2e4-94d5-4741-9a73-cd9ce5a6d69f"),
                Module = "workforce-admin",
                Action = "delete",
                Key = "workforce-admin.delete",
                Label = "Delete",
                DisplayOrder = 8,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("ec1f3291-ebb5-4b79-abfe-bf6a8702f895"),
                Module = "engagement",
                Action = "view",
                Key = "engagement.view",
                Label = "View",
                DisplayOrder = 9,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("46eb9271-252f-428e-bdbd-756c36d39203"),
                Module = "engagement",
                Action = "create",
                Key = "engagement.create",
                Label = "Create",
                DisplayOrder = 9,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("4852ff8b-e34b-42fc-8beb-944d4f0143d8"),
                Module = "engagement",
                Action = "edit",
                Key = "engagement.edit",
                Label = "Edit",
                DisplayOrder = 9,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("256f8ba6-c0bb-45ab-a9ad-018a4bfaa5ee"),
                Module = "engagement",
                Action = "delete",
                Key = "engagement.delete",
                Label = "Delete",
                DisplayOrder = 9,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("9558c7d8-d90e-44cc-b361-4f897230103a"),
                Module = "reports-analytics",
                Action = "view",
                Key = "reports-analytics.view",
                Label = "View",
                DisplayOrder = 10,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("b7bd020c-bf4f-4e36-a501-b4f68dd1a096"),
                Module = "reports-analytics",
                Action = "create",
                Key = "reports-analytics.create",
                Label = "Create",
                DisplayOrder = 10,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("3dca5a94-952c-427b-919b-206a9183bda5"),
                Module = "reports-analytics",
                Action = "edit",
                Key = "reports-analytics.edit",
                Label = "Edit",
                DisplayOrder = 10,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("54ae37a9-186d-466a-b5df-70b7c68a7679"),
                Module = "reports-analytics",
                Action = "delete",
                Key = "reports-analytics.delete",
                Label = "Delete",
                DisplayOrder = 10,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("6e2c1b3a-8f4d-4a2e-9c7b-1a5e3d8f6b2c"),
                Module = "identity-administration",
                Action = "view",
                Key = "identity-administration.view",
                Label = "View",
                DisplayOrder = 11,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("7f3d2c4b-9a5e-4b3f-8d6c-2b6f4e9a7c3d"),
                Module = "identity-administration",
                Action = "create",
                Key = "identity-administration.create",
                Label = "Create",
                DisplayOrder = 11,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("8a4e3d5c-0b6f-4c40-9e7d-3c7a5f0b8d4e"),
                Module = "identity-administration",
                Action = "edit",
                Key = "identity-administration.edit",
                Label = "Edit",
                DisplayOrder = 11,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            },
            new
            {
                Id = Guid.Parse("9b5f4e6d-1c70-4d51-af8e-4d8b60c19e5f"),
                Module = "identity-administration",
                Action = "delete",
                Key = "identity-administration.delete",
                Label = "Delete",
                DisplayOrder = 11,
                IsActive = true,
                CreatedAt = new DateTime(
                    2026,
                    1,
                    1,
                    0,
                    0,
                    0,
                    DateTimeKind.Utc),
                CreatedBy = (Guid?)null,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (Guid?)null,
                IsDeleted = false,
                DeletedAt = (DateTime?)null,
                DeletedBy = (Guid?)null
            }
        };
    }
}
