import type { Patient } from '@hms/shared';

/**
 * Seed data for the demo/offline fallback (see mockPatientsStore.ts) — lets the Patient
 * Management UI be demoed for client sign-off before the backend is wired up. Not used
 * once the API is reachable. Modeled on a Tirunelveli, Tamil Nadu hospital — departments
 * and consultants are drawn from config/hospitalData.ts so the same doctors recur here
 * and in the dashboard/login mock data.
 */
export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'mock-001',
    uhid: 'NH20260001',
    title: 'Mr',
    firstName: 'Aravind',
    lastName: 'Nadar',
    dateOfBirth: '1988-04-12',
    age: 38,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '12, Bharathiyar Street',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9442112345',
    primaryPhoneRelation: 'Self',
    email: 'aravind.nadar@example.com',
    profession: 'Textile Merchant',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Meena Nadar',
    emergencyContactPhone: '9442112346',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-001',
      registrationNumber: 'REG20260001',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      createdAt: '2026-07-20T09:15:00.000Z',
    },
    createdAt: '2026-07-20T09:15:00.000Z',
  },
  {
    id: 'mock-002',
    uhid: 'NH20260002',
    title: 'Mrs',
    firstName: 'Kavitha',
    lastName: 'Pillai',
    dateOfBirth: '1975-11-02',
    age: 50,
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '45, Perumal Koil Street',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9843223456',
    primaryPhoneRelation: 'Self',
    email: 'kavitha.pillai@example.com',
    profession: 'School Teacher',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Ravi Pillai',
    emergencyContactPhone: '9843223457',
    hasKnownAllergy: true,
    allergyType: 'Drug - Penicillin',
    allergySeverity: 'Moderate',
    currentRegistration: {
      id: 'mock-reg-002',
      registrationNumber: 'REG20260002',
      encounterType: 'IP',
      modeOfArrival: 'Ambulance',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Kumar',
      admissionType: 'NMLC',
      createdAt: '2026-07-21T11:40:00.000Z',
    },
    createdAt: '2026-07-21T11:40:00.000Z',
  },
  {
    id: 'mock-003',
    uhid: 'NH20260003',
    title: 'Master',
    firstName: 'Praveen',
    lastName: 'Iyer',
    dateOfBirth: '2018-02-19',
    age: 8,
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '7, Krishnan Kovil Street',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9994334567',
    primaryPhoneRelation: 'Father',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Elumalai Iyer',
    emergencyContactPhone: '9994334567',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-003',
      registrationNumber: 'REG20260003',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-21T14:05:00.000Z',
    },
    createdAt: '2026-07-21T14:05:00.000Z',
  },
  {
    id: 'mock-004',
    uhid: 'NH20260004',
    title: 'Ms',
    firstName: 'Nandhini',
    lastName: 'Thevar',
    dateOfBirth: '1996-07-30',
    age: 29,
    gender: 'Female',
    bloodGroup: 'ABPositive',
    addressLine1: '18, Nadar Street',
    addressLine3: 'Sankarankovil',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627756',
    primaryPhone: '8940445678',
    primaryPhoneRelation: 'Self',
    email: 'nandhini.thevar@example.com',
    profession: 'Graphic Designer',
    emergencyContactRelationship: 'Sister',
    emergencyContactName: 'Valli Thevar',
    emergencyContactPhone: '8940445679',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-004',
      registrationNumber: 'REG20260004',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-22T02:50:00.000Z',
    },
    createdAt: '2026-07-22T02:50:00.000Z',
  },
  {
    id: 'mock-005',
    uhid: 'NH20260005',
    title: 'Mr',
    firstName: 'Vignesh',
    lastName: 'Rajan',
    dateOfBirth: '1982-09-14',
    age: 43,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '23, Agraharam Street',
    addressLine3: 'Ambasamudram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627401',
    primaryPhone: '9865556789',
    primaryPhoneRelation: 'Self',
    email: 'vignesh.rajan@example.com',
    profession: 'Farmer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Selvi Rajan',
    emergencyContactPhone: '9865556790',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-005',
      registrationNumber: 'REG20260005',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Arun Kumar',
      createdAt: '2026-07-22T08:30:00.000Z',
    },
    createdAt: '2026-07-22T08:30:00.000Z',
  },
  {
    id: 'mock-006',
    uhid: 'NH20260006',
    title: 'Mrs',
    firstName: 'Keerthana',
    lastName: 'Chettiar',
    dateOfBirth: '1990-01-25',
    age: 36,
    gender: 'Female',
    bloodGroup: 'BNegative',
    addressLine1: '56, Chidambara Nagar',
    addressLine3: 'Pettai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627004',
    primaryPhone: '9600667890',
    primaryPhoneRelation: 'Self',
    email: 'keerthana.chettiar@example.com',
    profession: 'Boutique Owner',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Kannan Chettiar',
    emergencyContactPhone: '9600667891',
    hasKnownAllergy: true,
    allergyType: 'Food - Peanuts',
    allergySeverity: 'Severe',
    currentRegistration: {
      id: 'mock-reg-006',
      registrationNumber: 'REG20260006',
      encounterType: 'OP',
      modeOfArrival: 'Referred',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      referralSource: 'Dr. Perumal — Nellai Family Clinic',
      createdAt: '2026-07-22T12:10:00.000Z',
    },
    createdAt: '2026-07-22T12:10:00.000Z',
  },
  {
    id: 'mock-007',
    uhid: 'NH20260007',
    title: 'Mr',
    firstName: 'Saravanan',
    lastName: 'Nadesan',
    dateOfBirth: '1965-06-08',
    age: 61,
    gender: 'Male',
    bloodGroup: 'APositive',
    addressLine1: '9, Vannarpettai High Road',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627003',
    primaryPhone: '9787778901',
    primaryPhoneRelation: 'Self',
    profession: 'Retired Government Officer',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Bhuvaneswari Nadesan',
    emergencyContactPhone: '9787778902',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-007',
      registrationNumber: 'REG20260007',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'Neurology',
      consultant: 'Dr. Priya',
      admissionType: 'NMLC',
      createdAt: '2026-07-23T07:20:00.000Z',
    },
    createdAt: '2026-07-23T07:20:00.000Z',
  },
  {
    id: 'mock-008',
    uhid: 'NH20260008',
    title: 'Miss',
    firstName: 'Divya',
    lastName: 'Maran',
    dateOfBirth: '2001-03-17',
    age: 25,
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '31, South Bypass Road',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '8870889012',
    primaryPhoneRelation: 'Self',
    email: 'divya.maran@example.com',
    profession: 'Student',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Malathi Maran',
    emergencyContactPhone: '8870889013',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-008',
      registrationNumber: 'REG20260008',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Radiology',
      consultant: 'Dr. Nirmala',
      createdAt: '2026-07-23T10:45:00.000Z',
    },
    createdAt: '2026-07-23T10:45:00.000Z',
  },
  {
    id: 'mock-009',
    uhid: 'NH20260009',
    title: 'Mr',
    firstName: 'Karthik',
    lastName: 'Selvam',
    dateOfBirth: '1979-12-05',
    age: 46,
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '4, Trivandrum Road',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9445990123',
    primaryPhoneRelation: 'Self',
    email: 'karthik.selvam@example.com',
    profession: 'Bank Manager',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Parvathi Selvam',
    emergencyContactPhone: '9445990124',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-009',
      registrationNumber: 'REG20260009',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      admissionType: 'MLC',
      createdAt: '2026-07-23T19:55:00.000Z',
    },
    createdAt: '2026-07-23T19:55:00.000Z',
  },
  {
    id: 'mock-010',
    uhid: 'NH20260010',
    title: 'Mrs',
    firstName: 'Gomathi',
    lastName: 'Raj',
    dateOfBirth: '1985-05-22',
    age: 41,
    gender: 'Female',
    bloodGroup: 'ABNegative',
    addressLine1: '67, Reddiyarpatti Road',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9500112345',
    primaryPhoneRelation: 'Self',
    email: 'gomathi.raj@example.com',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Anbu Raj',
    emergencyContactPhone: '9500112346',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-010',
      registrationNumber: 'REG20260010',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Gynecology',
      consultant: 'Dr. Balasubramanian',
      createdAt: '2026-07-24T06:30:00.000Z',
    },
    createdAt: '2026-07-24T06:30:00.000Z',
  },
  {
    id: 'mock-011',
    uhid: 'NH20260011',
    title: 'Baby',
    firstName: 'Muthu',
    lastName: 'Kumar',
    dateOfBirth: '2025-12-01',
    age: 0,
    gender: 'Male',
    bloodGroup: 'Unknown',
    addressLine1: '14, Melapalayam Main Road',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9500001234',
    primaryPhoneRelation: 'Mother',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Senthamarai Kumar',
    emergencyContactPhone: '9500001234',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-011',
      registrationNumber: 'REG20260011',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-24T09:10:00.000Z',
    },
    createdAt: '2026-07-24T09:10:00.000Z',
  },
  {
    id: 'mock-012',
    uhid: 'NH20260012',
    title: 'Mr',
    firstName: 'Manoj',
    lastName: 'Bharathi',
    dateOfBirth: '1993-08-19',
    age: 32,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '88, Vannarpettai',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627003',
    primaryPhone: '9445445678',
    primaryPhoneRelation: 'Self',
    email: 'manoj.bharathi@example.com',
    profession: 'Marketing Manager',
    emergencyContactRelationship: 'Brother',
    emergencyContactName: 'Ilango Bharathi',
    emergencyContactPhone: '9445445679',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-012',
      registrationNumber: 'REG20260012',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-24T13:25:00.000Z',
    },
    createdAt: '2026-07-24T13:25:00.000Z',
  },
  {
    id: 'mock-013',
    uhid: 'NH20260013',
    title: 'Ms',
    firstName: 'Harini',
    lastName: 'Murugan',
    dateOfBirth: '1998-10-11',
    age: 27,
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '3, Anna Nagar',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9865223456',
    primaryPhoneRelation: 'Self',
    email: 'harini.murugan@example.com',
    profession: 'Nurse',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Chitra Murugan',
    emergencyContactPhone: '9865223457',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-013',
      registrationNumber: 'REG20260013',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Arun Kumar',
      createdAt: '2026-07-25T05:40:00.000Z',
    },
    createdAt: '2026-07-25T05:40:00.000Z',
  },
  {
    id: 'mock-014',
    uhid: 'NH20260014',
    title: 'Mr',
    firstName: 'Rajesh',
    lastName: 'Alagappan',
    dateOfBirth: '1970-02-28',
    age: 56,
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '21, East Car Street',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '8940667890',
    primaryPhoneRelation: 'Self',
    profession: 'Shop Owner',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Kannan Alagappan',
    emergencyContactPhone: '8940667891',
    hasKnownAllergy: true,
    allergyType: 'Drug - Sulfa',
    allergySeverity: 'Mild',
    currentRegistration: {
      id: 'mock-reg-014',
      registrationNumber: 'REG20260014',
      encounterType: 'IP',
      modeOfArrival: 'Referred',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'NMLC',
      referralSource: 'Dr. Murugesan — Nellai Family Clinic',
      createdAt: '2026-07-25T10:15:00.000Z',
    },
    createdAt: '2026-07-25T10:15:00.000Z',
  },
  {
    id: 'mock-015',
    uhid: 'NH20260015',
    title: 'Mrs',
    firstName: 'Abirami',
    lastName: 'Natarajan',
    dateOfBirth: '1958-09-09',
    age: 67,
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '9, West Car Street',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9787556789',
    primaryPhoneRelation: 'Self',
    profession: 'Retired',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Yazhini Natarajan',
    emergencyContactPhone: '9787556790',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-015',
      registrationNumber: 'REG20260015',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Radiology',
      consultant: 'Dr. Nirmala',
      createdAt: '2026-07-25T14:50:00.000Z',
    },
    createdAt: '2026-07-25T14:50:00.000Z',
  },
  {
    id: 'mock-016',
    uhid: 'NH20260016',
    title: 'Ms',
    firstName: 'Deepika',
    lastName: 'Elango',
    dateOfBirth: '1991-04-04',
    age: 35,
    gender: 'Female',
    bloodGroup: 'ABPositive',
    addressLine1: '55, Court Road',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9600334567',
    primaryPhoneRelation: 'Self',
    email: 'deepika.elango@example.com',
    profession: 'Advocate',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Perumal Elango',
    emergencyContactPhone: '9600334568',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-016',
      registrationNumber: 'REG20260016',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'ENT',
      consultant: 'Dr. Lakshmi',
      createdAt: '2026-07-25T20:05:00.000Z',
    },
    createdAt: '2026-07-25T20:05:00.000Z',
  },
  {
    id: 'mock-017',
    uhid: 'NH20260017',
    title: 'Ms',
    firstName: 'Sangeetha',
    lastName: 'Shanmugam',
    dateOfBirth: '1994-06-16',
    age: 32,
    gender: 'Female',
    bloodGroup: 'BNegative',
    addressLine1: '10, Nanguneri Main Road',
    addressLine3: 'Nanguneri',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627106',
    primaryPhone: '9865778901',
    primaryPhoneRelation: 'Self',
    email: 'sangeetha.shanmugam@example.com',
    profession: 'College Lecturer',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Murugesan Shanmugam',
    emergencyContactPhone: '9865778902',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-017',
      registrationNumber: 'REG20260017',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      createdAt: '2026-07-26T04:15:00.000Z',
    },
    createdAt: '2026-07-26T04:15:00.000Z',
  },
  {
    id: 'mock-018',
    uhid: 'NH20260018',
    title: 'Mr',
    firstName: 'Vetrivel',
    lastName: 'Vellaiyan',
    dateOfBirth: '1987-01-30',
    age: 39,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '33, Vallioor Bypass Road',
    addressLine3: 'Vallioor',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627117',
    primaryPhone: '9600889012',
    primaryPhoneRelation: 'Self',
    email: 'vetrivel.vellaiyan@example.com',
    profession: 'Civil Engineer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Kalaiselvi Vellaiyan',
    emergencyContactPhone: '9600889013',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-018',
      registrationNumber: 'REG20260018',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-26T06:30:00.000Z',
    },
    createdAt: '2026-07-26T06:30:00.000Z',
  },
];
