import type { Patient } from '@hms/shared';
import { calculateAge } from './detailedAge';

/**
 * Seed data for the demo/offline fallback (see mockPatientsStore.ts) — lets the Patient
 * Management UI be demoed for client sign-off before the backend is wired up. Not used
 * once the API is reachable. Modeled on a Tirunelveli, Tamil Nadu hospital — departments
 * and consultants are drawn from config/hospitalData.ts so the same doctors recur here
 * and in the dashboard/login mock data.
 *
 * No `age` here on purpose — it's derived from dateOfBirth below (and again on every read
 * in mockPatientsStore.ts), matching the backend's Patient.Age computed property. A literal
 * age baked into seed data would just go stale as real time passes.
 */
const PATIENT_SEEDS: Array<Omit<Patient, 'age'>> = [
  {
    id: 'mock-001',
    uhid: 'NH20260001',
    title: 'Mr',
    firstName: 'Aravind',
    lastName: 'Nadar',
    dateOfBirth: '1988-04-12',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '12, Bharathiyar Street',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9442112345',
    primaryPhoneRelation: 'Self',
    email: 'aravind.nadar@example.com',
    profession: 'Textile Merchant',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Meena Nadar',
    emergencyContactPhone: '9442112346',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-001',
      registrationNumber: 'REG20260001',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      createdAt: '2026-07-20T09:15:00.000Z',
    },
    createdAt: '2026-07-20T09:15:00.000Z',
  },
  {
    id: 'mock-002',
    uhid: 'NH20260002',
    title: 'Mrs',
    firstName: 'Kavitha',
    lastName: 'Pillai',
    dateOfBirth: '1975-11-02',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '45, Perumal Koil Street',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9843223456',
    primaryPhoneRelation: 'Self',
    email: 'kavitha.pillai@example.com',
    profession: 'School Teacher',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Ravi Pillai',
    emergencyContactPhone: '9843223457',
    hasKnownAllergy: true,
    allergyType: 'Drug - Penicillin',
    allergySeverity: 'Moderate',
    currentRegistration: {
      id: 'mock-reg-002',
      registrationNumber: 'REG20260002',
      encounterType: 'IP',
      modeOfArrival: 'Ambulance',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Kumar',
      admissionType: 'NMLC',
      createdAt: '2026-07-21T11:40:00.000Z',
    },
    createdAt: '2026-07-21T11:40:00.000Z',
  },
  {
    id: 'mock-003',
    uhid: 'NH20260003',
    title: 'Master',
    firstName: 'Praveen',
    lastName: 'Iyer',
    dateOfBirth: '2018-02-19',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '7, Krishnan Kovil Street',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9994334567',
    primaryPhoneRelation: 'Father',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Elumalai Iyer',
    emergencyContactPhone: '9994334567',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-003',
      registrationNumber: 'REG20260003',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-21T14:05:00.000Z',
    },
    createdAt: '2026-07-21T14:05:00.000Z',
  },
  {
    id: 'mock-004',
    uhid: 'NH20260004',
    title: 'Ms',
    firstName: 'Nandhini',
    lastName: 'Thevar',
    dateOfBirth: '1996-07-30',
    gender: 'Female',
    bloodGroup: 'ABPositive',
    addressLine1: '18, Nadar Street',
    addressLine3: 'Sankarankovil',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627756',
    primaryPhone: '8940445678',
    primaryPhoneRelation: 'Self',
    email: 'nandhini.thevar@example.com',
    profession: 'Graphic Designer',
    emergencyContactRelationship: 'Sister',
    emergencyContactName: 'Valli Thevar',
    emergencyContactPhone: '8940445679',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-004',
      registrationNumber: 'REG20260004',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-22T02:50:00.000Z',
    },
    createdAt: '2026-07-22T02:50:00.000Z',
  },
  {
    id: 'mock-005',
    uhid: 'NH20260005',
    title: 'Mr',
    firstName: 'Vignesh',
    lastName: 'Rajan',
    dateOfBirth: '1982-09-14',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '23, Agraharam Street',
    addressLine3: 'Ambasamudram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627401',
    primaryPhone: '9865556789',
    primaryPhoneRelation: 'Self',
    email: 'vignesh.rajan@example.com',
    profession: 'Farmer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Selvi Rajan',
    emergencyContactPhone: '9865556790',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-005',
      registrationNumber: 'REG20260005',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Arun Kumar',
      createdAt: '2026-07-22T08:30:00.000Z',
    },
    createdAt: '2026-07-22T08:30:00.000Z',
  },
  {
    id: 'mock-006',
    uhid: 'NH20260006',
    title: 'Mrs',
    firstName: 'Keerthana',
    lastName: 'Chettiar',
    dateOfBirth: '1990-01-25',
    gender: 'Female',
    bloodGroup: 'BNegative',
    addressLine1: '56, Chidambara Nagar',
    addressLine3: 'Pettai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627004',
    primaryPhone: '9600667890',
    primaryPhoneRelation: 'Self',
    email: 'keerthana.chettiar@example.com',
    profession: 'Boutique Owner',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Kannan Chettiar',
    emergencyContactPhone: '9600667891',
    hasKnownAllergy: true,
    allergyType: 'Food - Peanuts',
    allergySeverity: 'Severe',
    currentRegistration: {
      id: 'mock-reg-006',
      registrationNumber: 'REG20260006',
      encounterType: 'OP',
      modeOfArrival: 'Referred',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      referralSource: 'Dr. Perumal — Nellai Family Clinic',
      createdAt: '2026-07-22T12:10:00.000Z',
    },
    createdAt: '2026-07-22T12:10:00.000Z',
  },
  {
    id: 'mock-007',
    uhid: 'NH20260007',
    title: 'Mr',
    firstName: 'Saravanan',
    lastName: 'Nadesan',
    dateOfBirth: '1965-06-08',
    gender: 'Male',
    bloodGroup: 'APositive',
    addressLine1: '9, Vannarpettai High Road',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627003',
    primaryPhone: '9787778901',
    primaryPhoneRelation: 'Self',
    profession: 'Retired Government Officer',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Bhuvaneswari Nadesan',
    emergencyContactPhone: '9787778902',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-007',
      registrationNumber: 'REG20260007',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'Neurology',
      consultant: 'Dr. Priya',
      admissionType: 'NMLC',
      createdAt: '2026-07-23T07:20:00.000Z',
    },
    createdAt: '2026-07-23T07:20:00.000Z',
  },
  {
    id: 'mock-008',
    uhid: 'NH20260008',
    title: 'Miss',
    firstName: 'Divya',
    lastName: 'Maran',
    dateOfBirth: '2001-03-17',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '31, South Bypass Road',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '8870889012',
    primaryPhoneRelation: 'Self',
    email: 'divya.maran@example.com',
    profession: 'Student',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Malathi Maran',
    emergencyContactPhone: '8870889013',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-008',
      registrationNumber: 'REG20260008',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Radiology',
      consultant: 'Dr. Nirmala',
      createdAt: '2026-07-23T10:45:00.000Z',
    },
    createdAt: '2026-07-23T10:45:00.000Z',
  },
  {
    id: 'mock-009',
    uhid: 'NH20260009',
    title: 'Mr',
    firstName: 'Karthik',
    lastName: 'Selvam',
    dateOfBirth: '1979-12-05',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '4, Trivandrum Road',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9445990123',
    primaryPhoneRelation: 'Self',
    email: 'karthik.selvam@example.com',
    profession: 'Bank Manager',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Parvathi Selvam',
    emergencyContactPhone: '9445990124',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-009',
      registrationNumber: 'REG20260009',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      admissionType: 'MLC',
      createdAt: '2026-07-23T19:55:00.000Z',
    },
    createdAt: '2026-07-23T19:55:00.000Z',
  },
  {
    id: 'mock-010',
    uhid: 'NH20260010',
    title: 'Mrs',
    firstName: 'Gomathi',
    lastName: 'Raj',
    dateOfBirth: '1985-05-22',
    gender: 'Female',
    bloodGroup: 'ABNegative',
    addressLine1: '67, Reddiyarpatti Road',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9500112345',
    primaryPhoneRelation: 'Self',
    email: 'gomathi.raj@example.com',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Anbu Raj',
    emergencyContactPhone: '9500112346',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-010',
      registrationNumber: 'REG20260010',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Gynecology',
      consultant: 'Dr. Balasubramanian',
      createdAt: '2026-07-24T06:30:00.000Z',
    },
    createdAt: '2026-07-24T06:30:00.000Z',
  },
  {
    id: 'mock-011',
    uhid: 'NH20260011',
    title: 'Baby',
    firstName: 'Muthu',
    lastName: 'Kumar',
    dateOfBirth: '2025-12-01',
    gender: 'Male',
    bloodGroup: 'Unknown',
    addressLine1: '14, Melapalayam Main Road',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9500001234',
    primaryPhoneRelation: 'Mother',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Senthamarai Kumar',
    emergencyContactPhone: '9500001234',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-011',
      registrationNumber: 'REG20260011',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-24T09:10:00.000Z',
    },
    createdAt: '2026-07-24T09:10:00.000Z',
  },
  {
    id: 'mock-012',
    uhid: 'NH20260012',
    title: 'Mr',
    firstName: 'Manoj',
    lastName: 'Bharathi',
    dateOfBirth: '1993-08-19',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '88, Vannarpettai',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627003',
    primaryPhone: '9445445678',
    primaryPhoneRelation: 'Self',
    email: 'manoj.bharathi@example.com',
    profession: 'Marketing Manager',
    emergencyContactRelationship: 'Brother',
    emergencyContactName: 'Ilango Bharathi',
    emergencyContactPhone: '9445445679',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-012',
      registrationNumber: 'REG20260012',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-24T13:25:00.000Z',
    },
    createdAt: '2026-07-24T13:25:00.000Z',
  },
  {
    id: 'mock-013',
    uhid: 'NH20260013',
    title: 'Ms',
    firstName: 'Harini',
    lastName: 'Murugan',
    dateOfBirth: '1998-10-11',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '3, Anna Nagar',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9865223456',
    primaryPhoneRelation: 'Self',
    email: 'harini.murugan@example.com',
    profession: 'Nurse',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Chitra Murugan',
    emergencyContactPhone: '9865223457',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-013',
      registrationNumber: 'REG20260013',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Arun Kumar',
      createdAt: '2026-07-25T05:40:00.000Z',
    },
    createdAt: '2026-07-25T05:40:00.000Z',
  },
  {
    id: 'mock-014',
    uhid: 'NH20260014',
    title: 'Mr',
    firstName: 'Rajesh',
    lastName: 'Alagappan',
    dateOfBirth: '1970-02-28',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '21, East Car Street',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '8940667890',
    primaryPhoneRelation: 'Self',
    profession: 'Shop Owner',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Kannan Alagappan',
    emergencyContactPhone: '8940667891',
    hasKnownAllergy: true,
    allergyType: 'Drug - Sulfa',
    allergySeverity: 'Mild',
    currentRegistration: {
      id: 'mock-reg-014',
      registrationNumber: 'REG20260014',
      encounterType: 'IP',
      modeOfArrival: 'Referred',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'NMLC',
      referralSource: 'Dr. Murugesan — Nellai Family Clinic',
      createdAt: '2026-07-25T10:15:00.000Z',
    },
    createdAt: '2026-07-25T10:15:00.000Z',
  },
  {
    id: 'mock-015',
    uhid: 'NH20260015',
    title: 'Mrs',
    firstName: 'Abirami',
    lastName: 'Natarajan',
    dateOfBirth: '1958-09-09',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '9, West Car Street',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9787556789',
    primaryPhoneRelation: 'Self',
    profession: 'Retired',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Yazhini Natarajan',
    emergencyContactPhone: '9787556790',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-015',
      registrationNumber: 'REG20260015',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Radiology',
      consultant: 'Dr. Nirmala',
      createdAt: '2026-07-25T14:50:00.000Z',
    },
    createdAt: '2026-07-25T14:50:00.000Z',
  },
  {
    id: 'mock-016',
    uhid: 'NH20260016',
    title: 'Ms',
    firstName: 'Deepika',
    lastName: 'Elango',
    dateOfBirth: '1991-04-04',
    gender: 'Female',
    bloodGroup: 'ABPositive',
    addressLine1: '55, Court Road',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9600334567',
    primaryPhoneRelation: 'Self',
    email: 'deepika.elango@example.com',
    profession: 'Advocate',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Perumal Elango',
    emergencyContactPhone: '9600334568',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-016',
      registrationNumber: 'REG20260016',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'ENT',
      consultant: 'Dr. Lakshmi',
      createdAt: '2026-07-25T20:05:00.000Z',
    },
    createdAt: '2026-07-25T20:05:00.000Z',
  },
  {
    id: 'mock-017',
    uhid: 'NH20260017',
    title: 'Ms',
    firstName: 'Sangeetha',
    lastName: 'Shanmugam',
    dateOfBirth: '1994-06-16',
    gender: 'Female',
    bloodGroup: 'BNegative',
    addressLine1: '10, Nanguneri Main Road',
    addressLine3: 'Nanguneri',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627106',
    primaryPhone: '9865778901',
    primaryPhoneRelation: 'Self',
    email: 'sangeetha.shanmugam@example.com',
    profession: 'College Lecturer',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Murugesan Shanmugam',
    emergencyContactPhone: '9865778902',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-017',
      registrationNumber: 'REG20260017',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      createdAt: '2026-07-26T04:15:00.000Z',
    },
    createdAt: '2026-07-26T04:15:00.000Z',
  },
  {
    id: 'mock-018',
    uhid: 'NH20260018',
    title: 'Mr',
    firstName: 'Vetrivel',
    lastName: 'Vellaiyan',
    dateOfBirth: '1987-01-30',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '33, Valliyur Bypass Road',
    addressLine3: 'Valliyur',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627117',
    primaryPhone: '9600889012',
    primaryPhoneRelation: 'Self',
    email: 'vetrivel.vellaiyan@example.com',
    profession: 'Civil Engineer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Kalaiselvi Vellaiyan',
    emergencyContactPhone: '9600889013',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-018',
      registrationNumber: 'REG20260018',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-26T06:30:00.000Z',
    },
    createdAt: '2026-07-26T06:30:00.000Z',
  },
  {
    id: 'mock-019',
    uhid: 'NH20260019',
    title: 'Mr',
    firstName: 'Selvaraj',
    lastName: 'Muthu',
    dateOfBirth: '1968-03-14',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '2, Barracks Road',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9442112019',
    primaryPhoneRelation: 'Self',
    profession: 'Retired Postal Employee',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Prabhu Muthu',
    emergencyContactPhone: '9442112020',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260019.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260019-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-019',
      registrationNumber: 'REG20260019',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-26T09:10:00.000Z',
    },
    createdAt: '2026-07-26T09:10:00.000Z',
  },
  {
    id: 'mock-020',
    uhid: 'NH20260020',
    title: 'Mrs',
    firstName: 'Poornima',
    lastName: 'Krishnan',
    dateOfBirth: '1981-06-02',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '19, Gandhi Nagar',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9843223020',
    primaryPhoneRelation: 'Self',
    email: 'poornima.krishnan@example.com',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Krishnan Velu',
    emergencyContactPhone: '9843223021',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260020.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260020-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-020',
      registrationNumber: 'REG20260020',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Gynecology',
      consultant: 'Dr. Balasubramanian',
      createdAt: '2026-07-26T09:45:00.000Z',
    },
    createdAt: '2026-07-26T09:45:00.000Z',
  },
  {
    id: 'mock-021',
    uhid: 'NH20260021',
    title: 'Miss',
    firstName: 'Kayal Vizhi',
    lastName: 'Antony',
    dateOfBirth: '2004-02-10',
    gender: 'Female',
    bloodGroup: 'BPositive',
    addressLine1: '5, Church Lane',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9994334021',
    primaryPhoneRelation: 'Self',
    email: 'kayalvizhi.antony@example.com',
    profession: 'Nursing Student',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Antony Raj',
    emergencyContactPhone: '9994334022',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260021.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260021-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-021',
      registrationNumber: 'REG20260021',
      encounterType: 'DayCare',
      modeOfArrival: 'Referred',
      department: 'ENT',
      consultant: 'Dr. Lakshmi',
      referralSource: 'Family recommendation — relative treated earlier at Nellai Hospitals',
      createdAt: '2026-07-26T10:20:00.000Z',
    },
    createdAt: '2026-07-26T10:20:00.000Z',
  },
  {
    id: 'mock-022',
    uhid: 'NH20260022',
    title: 'Master',
    firstName: 'Arjun',
    lastName: 'Prakash',
    dateOfBirth: '2016-01-20',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '14, Trivandrum High Road',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '8940445022',
    primaryPhoneRelation: 'Father',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Prakash Raman',
    emergencyContactPhone: '8940445022',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-022',
      registrationNumber: 'REG20260022',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-26T11:05:00.000Z',
    },
    createdAt: '2026-07-26T11:05:00.000Z',
  },
  {
    id: 'mock-023',
    uhid: 'NH20260023',
    title: 'Mr',
    firstName: 'Mohammed',
    lastName: 'Ismail',
    dateOfBirth: '1976-05-05',
    gender: 'Male',
    bloodGroup: 'ABPositive',
    addressLine1: '61, Mosque Street',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9865556023',
    primaryPhoneRelation: 'Self',
    email: 'mohammed.ismail@example.com',
    profession: 'Textile Wholesaler',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Fathima Ismail',
    emergencyContactPhone: '9865556024',
    hasKnownAllergy: true,
    allergyType: 'Drug - Aspirin',
    allergySeverity: 'Moderate',
    photoPath: '/uploads/patients/photos/NH20260023.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260023-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-023',
      registrationNumber: 'REG20260023',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'NMLC',
      createdAt: '2026-07-26T12:40:00.000Z',
    },
    createdAt: '2026-07-26T12:40:00.000Z',
  },
  {
    id: 'mock-024',
    uhid: 'NH20260024',
    title: 'Mrs',
    firstName: 'Fathima',
    lastName: 'Beevi',
    dateOfBirth: '1979-07-18',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '8, Angel Nagar',
    addressLine3: 'Palayamkottai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627002',
    primaryPhone: '9600667024',
    primaryPhoneRelation: 'Self',
    email: 'fathima.beevi@example.com',
    profession: 'Boutique Owner',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Ismail Basha',
    emergencyContactPhone: '9600667025',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260024.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260024-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-024',
      registrationNumber: 'REG20260024',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      createdAt: '2026-07-26T13:15:00.000Z',
    },
    createdAt: '2026-07-26T13:15:00.000Z',
  },
  {
    id: 'mock-025',
    uhid: 'NH20260025',
    title: 'Mr',
    firstName: 'Elango',
    lastName: 'Muthusamy',
    dateOfBirth: '1963-04-25',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '27, Weavers Colony',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9787778025',
    primaryPhoneRelation: 'Self',
    profession: 'Retired Handloom Weaver',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Ilango Muthusamy',
    emergencyContactPhone: '9787778026',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260025.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260025-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-025',
      registrationNumber: 'REG20260025',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Kumar',
      admissionType: 'NMLC',
      createdAt: '2026-07-26T14:50:00.000Z',
    },
    createdAt: '2026-07-26T14:50:00.000Z',
  },
  {
    id: 'mock-026',
    uhid: 'NH20260026',
    title: 'Baby',
    firstName: 'Devi',
    lastName: 'Kannan',
    dateOfBirth: '2026-03-15',
    gender: 'Female',
    bloodGroup: 'Unknown',
    addressLine1: '33, Krishnan Kovil Street',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9629001026',
    primaryPhoneRelation: 'Mother',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Kavya Kannan',
    emergencyContactPhone: '9629001026',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-026',
      registrationNumber: 'REG20260026',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-26T15:30:00.000Z',
    },
    createdAt: '2026-07-26T15:30:00.000Z',
  },
  {
    id: 'mock-027',
    uhid: 'NH20260027',
    title: 'Ms',
    firstName: 'Iniya',
    lastName: 'Selvi',
    dateOfBirth: '2007-06-30',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '41, South Street',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9655334027',
    primaryPhoneRelation: 'Self',
    profession: 'College Student',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Selvam Raj',
    emergencyContactPhone: '9655334028',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-027',
      registrationNumber: 'REG20260027',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-26T18:05:00.000Z',
    },
    createdAt: '2026-07-26T18:05:00.000Z',
  },
  {
    id: 'mock-028',
    uhid: 'NH20260028',
    title: 'Mr',
    firstName: 'Rajkumar',
    lastName: 'Ayyanar',
    dateOfBirth: '1988-02-14',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '16, Bus Stand Road',
    addressLine3: 'Melapalayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627005',
    primaryPhone: '9884556028',
    primaryPhoneRelation: 'Self',
    profession: 'Auto Driver',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Devika Ayyanar',
    emergencyContactPhone: '9884556029',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260028.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260028-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-028',
      registrationNumber: 'REG20260028',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-26T19:40:00.000Z',
    },
    createdAt: '2026-07-26T19:40:00.000Z',
  },
  {
    id: 'mock-029',
    uhid: 'NH20260029',
    title: 'Mrs',
    firstName: 'Chellammal',
    lastName: 'Perumal',
    dateOfBirth: '1956-01-09',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '3, Agraharam Street',
    addressLine3: 'Pettai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627004',
    primaryPhone: '9791223029',
    primaryPhoneRelation: 'Self',
    profession: 'Retired',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Banumathi Perumal',
    emergencyContactPhone: '9791223030',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260029.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260029-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-029',
      registrationNumber: 'REG20260029',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      createdAt: '2026-07-27T07:15:00.000Z',
    },
    createdAt: '2026-07-27T07:15:00.000Z',
  },
  {
    id: 'mock-030',
    uhid: 'NH20260030',
    title: 'Mr',
    firstName: 'Ganesan',
    lastName: 'Pandi',
    dateOfBirth: '1985-03-22',
    gender: 'Male',
    bloodGroup: 'APositive',
    addressLine1: '22, Bazaar Street',
    addressLine3: 'Pettai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627004',
    primaryPhone: '9976445030',
    primaryPhoneRelation: 'Self',
    email: 'ganesan.pandi@example.com',
    profession: 'Goldsmith',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Rathi Pandi',
    emergencyContactPhone: '9976445031',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260030.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260030-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-030',
      registrationNumber: 'REG20260030',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Arun Kumar',
      createdAt: '2026-07-27T08:00:00.000Z',
    },
    createdAt: '2026-07-27T08:00:00.000Z',
  },
  {
    id: 'mock-031',
    uhid: 'NH20260031',
    title: 'Ms',
    firstName: 'Swetha',
    lastName: 'Ganesan',
    dateOfBirth: '2010-07-01',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '48, Court Road',
    addressLine3: 'Pettai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627004',
    primaryPhone: '9003556031',
    primaryPhoneRelation: 'Father',
    profession: 'School Student',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Ganesan Muthiah',
    emergencyContactPhone: '9003556031',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-031',
      registrationNumber: 'REG20260031',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'ENT',
      consultant: 'Dr. Lakshmi',
      createdAt: '2026-07-27T08:45:00.000Z',
    },
    createdAt: '2026-07-27T08:45:00.000Z',
  },
  {
    id: 'mock-032',
    uhid: 'NH20260032',
    title: 'Mr',
    firstName: 'Antony',
    lastName: 'Xavier',
    dateOfBirth: '1971-05-19',
    gender: 'Male',
    bloodGroup: 'BNegative',
    addressLine1: '14, St. Thomas Nagar',
    addressLine3: 'Pettai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627004',
    primaryPhone: '9843332032',
    primaryPhoneRelation: 'Self',
    email: 'antony.xavier@example.com',
    profession: 'Church Pastor',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Mary Xavier',
    emergencyContactPhone: '9843332033',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260032.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260032-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-032',
      registrationNumber: 'REG20260032',
      encounterType: 'OP',
      modeOfArrival: 'Referred',
      department: 'Neurology',
      consultant: 'Dr. Priya',
      referralSource: 'Dr. Selvakumar — Pettai Family Clinic',
      createdAt: '2026-07-27T09:20:00.000Z',
    },
    createdAt: '2026-07-27T09:20:00.000Z',
  },
  {
    id: 'mock-033',
    uhid: 'NH20260033',
    title: 'Mr',
    firstName: 'Loganathan',
    lastName: 'Muthiah',
    dateOfBirth: '1992-04-08',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '9, Big Bazaar Street',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '9442223033',
    primaryPhoneRelation: 'Self',
    email: 'loganathan.muthiah@example.com',
    profession: 'Rice Mill Owner',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Kalaivani Muthiah',
    emergencyContactPhone: '9442223034',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260033.jpg',
    idProofType: 'DrivingLicense',
    idProofPath: '/uploads/patients/id-proofs/NH20260033-dl.pdf',
    currentRegistration: {
      id: 'mock-reg-033',
      registrationNumber: 'REG20260033',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-27T10:05:00.000Z',
    },
    createdAt: '2026-07-27T10:05:00.000Z',
  },
  {
    id: 'mock-034',
    uhid: 'NH20260034',
    title: 'Mrs',
    firstName: 'Amutha',
    lastName: 'Rajendran',
    dateOfBirth: '1997-06-12',
    gender: 'Female',
    bloodGroup: 'BPositive',
    addressLine1: '25, East Car Street',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '9787889034',
    primaryPhoneRelation: 'Self',
    email: 'amutha.rajendran@example.com',
    profession: 'Anganwadi Worker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Rajendran Pillai',
    emergencyContactPhone: '9787889035',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260034.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260034-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-034',
      registrationNumber: 'REG20260034',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      createdAt: '2026-07-27T11:30:00.000Z',
    },
    createdAt: '2026-07-27T11:30:00.000Z',
  },
  {
    id: 'mock-035',
    uhid: 'NH20260035',
    title: 'Master',
    firstName: 'Yogesh',
    lastName: 'Kannan',
    dateOfBirth: '2013-02-27',
    gender: 'Male',
    bloodGroup: 'ABPositive',
    addressLine1: '31, Middle Street',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '9843667035',
    primaryPhoneRelation: 'Mother',
    profession: 'School Student',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Dhanam Kannan',
    emergencyContactPhone: '9843667035',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-035',
      registrationNumber: 'REG20260035',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-27T12:10:00.000Z',
    },
    createdAt: '2026-07-27T12:10:00.000Z',
  },
  {
    id: 'mock-036',
    uhid: 'NH20260036',
    title: 'Mr',
    firstName: 'Petchimuthu',
    lastName: 'Konar',
    dateOfBirth: '1960-03-30',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '5, Sivan Kovil Street',
    addressLine3: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627811',
    primaryPhone: '9976223036',
    primaryPhoneRelation: 'Self',
    profession: 'Banana Farmer',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Alagesan Konar',
    emergencyContactPhone: '9976223037',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260036.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260036-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-036',
      registrationNumber: 'REG20260036',
      encounterType: 'IP',
      modeOfArrival: 'Referred',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'NMLC',
      referralSource: 'Camp referral — Rural Health Camp, Tenkasi',
      createdAt: '2026-07-27T13:35:00.000Z',
    },
    createdAt: '2026-07-27T13:35:00.000Z',
  },
  {
    id: 'mock-037',
    uhid: 'NH20260037',
    title: 'Mrs',
    firstName: 'Bhavani',
    lastName: 'Sundaram',
    dateOfBirth: '1989-07-06',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '17, Agraharam Street',
    addressLine3: 'Ambasamudram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627401',
    primaryPhone: '9944337037',
    primaryPhoneRelation: 'Self',
    email: 'bhavani.sundaram@example.com',
    profession: 'Staff Nurse',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Sundaram Pillai',
    emergencyContactPhone: '9944337038',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260037.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260037-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-037',
      registrationNumber: 'REG20260037',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Gynecology',
      consultant: 'Dr. Balasubramanian',
      createdAt: '2026-07-27T14:20:00.000Z',
    },
    createdAt: '2026-07-27T14:20:00.000Z',
  },
  {
    id: 'mock-038',
    uhid: 'NH20260038',
    title: 'Mr',
    firstName: 'Marimuthu',
    lastName: 'Velu',
    dateOfBirth: '1974-01-15',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '2, Kalakkad Road',
    addressLine3: 'Ambasamudram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627401',
    primaryPhone: '9994778038',
    primaryPhoneRelation: 'Self',
    profession: 'Rubber Plantation Worker',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Rani Velu',
    emergencyContactPhone: '9994778039',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-038',
      registrationNumber: 'REG20260038',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-27T16:00:00.000Z',
    },
    createdAt: '2026-07-27T16:00:00.000Z',
  },
  {
    id: 'mock-039',
    uhid: 'NH20260039',
    title: 'Ms',
    firstName: 'Janani',
    lastName: 'Bala',
    dateOfBirth: '2002-05-20',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '38, New Colony',
    addressLine3: 'Ambasamudram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627401',
    primaryPhone: '9092445039',
    primaryPhoneRelation: 'Self',
    email: 'janani.bala@example.com',
    profession: 'Software Engineer',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Kamala Bala',
    emergencyContactPhone: '9092445040',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260039.jpg',
    idProofType: 'Passport',
    idProofPath: '/uploads/patients/id-proofs/NH20260039-passport.pdf',
    currentRegistration: {
      id: 'mock-reg-039',
      registrationNumber: 'REG20260039',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'ENT',
      consultant: 'Dr. Lakshmi',
      createdAt: '2026-07-27T17:25:00.000Z',
    },
    createdAt: '2026-07-27T17:25:00.000Z',
  },
  {
    id: 'mock-040',
    uhid: 'NH20260040',
    title: 'Mr',
    firstName: 'Sivakumar',
    lastName: 'Devan',
    dateOfBirth: '1982-06-25',
    gender: 'Male',
    bloodGroup: 'ABNegative',
    addressLine1: '11, Workshop Road',
    addressLine3: 'Ambasamudram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627401',
    primaryPhone: '9843112040',
    primaryPhoneRelation: 'Self',
    profession: 'Two-Wheeler Mechanic',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Latha Devan',
    emergencyContactPhone: '9843112041',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260040.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260040-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-040',
      registrationNumber: 'REG20260040',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Kumar',
      createdAt: '2026-07-27T18:40:00.000Z',
    },
    createdAt: '2026-07-27T18:40:00.000Z',
  },
  {
    id: 'mock-041',
    uhid: 'NH20260041',
    title: 'Mrs',
    firstName: 'Vasanthi',
    lastName: 'Ramasamy',
    dateOfBirth: '1966-02-11',
    gender: 'Female',
    bloodGroup: 'BPositive',
    addressLine1: '6, Temple Street',
    addressLine3: 'Cheranmahadevi',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627105',
    primaryPhone: '9865442041',
    primaryPhoneRelation: 'Self',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Anandan Ramasamy',
    emergencyContactPhone: '9865442042',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260041.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260041-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-041',
      registrationNumber: 'REG20260041',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      createdAt: '2026-07-28T06:50:00.000Z',
    },
    createdAt: '2026-07-28T06:50:00.000Z',
  },
  {
    id: 'mock-042',
    uhid: 'NH20260042',
    title: 'Mr',
    firstName: 'Om Prakash',
    lastName: 'Iyer',
    dateOfBirth: '1995-04-17',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '4, Agraharam Street',
    addressLine3: 'Cheranmahadevi',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627105',
    primaryPhone: '9994223042',
    primaryPhoneRelation: 'Self',
    email: 'omprakash.iyer@example.com',
    profession: 'Temple Priest',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Sundara Iyer',
    emergencyContactPhone: '9994223043',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-042',
      registrationNumber: 'REG20260042',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-28T07:30:00.000Z',
    },
    createdAt: '2026-07-28T07:30:00.000Z',
  },
  {
    id: 'mock-043',
    uhid: 'NH20260043',
    title: 'Miss',
    firstName: 'Oviya',
    lastName: 'Prakash',
    dateOfBirth: '2020-03-05',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '4, Agraharam Street',
    addressLine3: 'Cheranmahadevi',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627105',
    primaryPhone: '9994223042',
    primaryPhoneRelation: 'Father',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Om Prakash Iyer',
    emergencyContactPhone: '9994223042',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-043',
      registrationNumber: 'REG20260043',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-28T07:35:00.000Z',
    },
    createdAt: '2026-07-28T07:35:00.000Z',
  },
  {
    id: 'mock-044',
    uhid: 'NH20260044',
    title: 'Mr',
    firstName: 'Nallathambi',
    lastName: 'Kaliappan',
    dateOfBirth: '1978-07-09',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '19, North Street',
    addressLine3: 'Valliyur',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627117',
    primaryPhone: '9787994044',
    primaryPhoneRelation: 'Self',
    profession: 'Farmer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Selvi Kaliappan',
    emergencyContactPhone: '9787994045',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260044.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260044-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-044',
      registrationNumber: 'REG20260044',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Kumar',
      admissionType: 'NMLC',
      createdAt: '2026-07-28T08:15:00.000Z',
    },
    createdAt: '2026-07-28T08:15:00.000Z',
  },
  {
    id: 'mock-045',
    uhid: 'NH20260045',
    title: 'Mrs',
    firstName: 'Thenmozhi',
    lastName: 'Ravi',
    dateOfBirth: '1993-05-28',
    gender: 'Female',
    bloodGroup: 'ANegative',
    addressLine1: '27, Bazaar Street',
    addressLine3: 'Valliyur',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627117',
    primaryPhone: '9865667045',
    primaryPhoneRelation: 'Self',
    email: 'thenmozhi.ravi@example.com',
    profession: 'Tailor',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Ravi Chandran',
    emergencyContactPhone: '9865667046',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260045.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260045-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-045',
      registrationNumber: 'REG20260045',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Arun Kumar',
      createdAt: '2026-07-28T09:00:00.000Z',
    },
    createdAt: '2026-07-28T09:00:00.000Z',
  },
  {
    id: 'mock-046',
    uhid: 'NH20260046',
    title: 'Mr',
    firstName: 'Daniel',
    lastName: 'Charles',
    dateOfBirth: '1999-06-14',
    gender: 'Male',
    bloodGroup: 'APositive',
    addressLine1: '8, Cross Street',
    addressLine3: 'Valliyur',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627117',
    primaryPhone: '9976889046',
    primaryPhoneRelation: 'Self',
    email: 'daniel.charles@example.com',
    profession: 'Mobile Shop Owner',
    emergencyContactRelationship: 'Brother',
    emergencyContactName: 'David Charles',
    emergencyContactPhone: '9976889047',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260046.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260046-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-046',
      registrationNumber: 'REG20260046',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      createdAt: '2026-07-28T09:40:00.000Z',
    },
    createdAt: '2026-07-28T09:40:00.000Z',
  },
  {
    id: 'mock-047',
    uhid: 'NH20260047',
    title: 'Mrs',
    firstName: 'Saroja',
    lastName: 'Kaliyaperumal',
    dateOfBirth: '1972-04-02',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '13, Jain Street',
    addressLine3: 'Nanguneri',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627106',
    primaryPhone: '9843778047',
    primaryPhoneRelation: 'Self',
    profession: 'Rice Trader',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Kaliyaperumal Doss',
    emergencyContactPhone: '9843778048',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260047.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260047-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-047',
      registrationNumber: 'REG20260047',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Neurology',
      consultant: 'Dr. Priya',
      createdAt: '2026-07-28T10:20:00.000Z',
    },
    createdAt: '2026-07-28T10:20:00.000Z',
  },
  {
    id: 'mock-048',
    uhid: 'NH20260048',
    title: 'Mr',
    firstName: 'Balan',
    lastName: 'Nagarajan',
    dateOfBirth: '1986-01-30',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '21, Panchayat Road',
    addressLine3: 'Nanguneri',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627106',
    primaryPhone: '9944667048',
    primaryPhoneRelation: 'Self',
    email: 'balan.nagarajan@example.com',
    profession: 'Village Administrative Officer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Bhuvana Nagarajan',
    emergencyContactPhone: '9944667049',
    hasKnownAllergy: true,
    allergyType: 'Drug - Sulfa',
    allergySeverity: 'Mild',
    photoPath: '/uploads/patients/photos/NH20260048.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260048-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-048',
      registrationNumber: 'REG20260048',
      encounterType: 'OP',
      modeOfArrival: 'Referred',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      referralSource: 'Dr. Murugesan — Nanguneri Family Clinic',
      createdAt: '2026-07-28T11:00:00.000Z',
    },
    createdAt: '2026-07-28T11:00:00.000Z',
  },
  {
    id: 'mock-049',
    uhid: 'NH20260049',
    title: 'Ms',
    firstName: 'Kavya',
    lastName: 'Balan',
    dateOfBirth: '2023-02-18',
    gender: 'Female',
    bloodGroup: 'Unknown',
    addressLine1: '21, Panchayat Road',
    addressLine3: 'Nanguneri',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627106',
    primaryPhone: '9944667048',
    primaryPhoneRelation: 'Father',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Balan Nagarajan',
    emergencyContactPhone: '9944667048',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-049',
      registrationNumber: 'REG20260049',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-28T12:30:00.000Z',
    },
    createdAt: '2026-07-28T12:30:00.000Z',
  },
  {
    id: 'mock-050',
    uhid: 'NH20260050',
    title: 'Mr',
    firstName: 'Rathinam',
    lastName: 'Sami',
    dateOfBirth: '1969-03-09',
    gender: 'Male',
    bloodGroup: 'ABPositive',
    addressLine1: '10, Weavers Street',
    addressLine3: 'Sankarankovil',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627756',
    primaryPhone: '9787223050',
    primaryPhoneRelation: 'Self',
    profession: 'Handloom Weaver',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Rajendran Sami',
    emergencyContactPhone: '9787223051',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260050.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260050-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-050',
      registrationNumber: 'REG20260050',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      admissionType: 'NMLC',
      createdAt: '2026-07-28T13:10:00.000Z',
    },
    createdAt: '2026-07-28T13:10:00.000Z',
  },
  {
    id: 'mock-051',
    uhid: 'NH20260051',
    title: 'Mrs',
    firstName: 'Indira',
    lastName: 'Gnanasekaran',
    dateOfBirth: '1980-05-15',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '6, South Car Street',
    addressLine3: 'Sankarankovil',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627756',
    primaryPhone: '9865223051',
    primaryPhoneRelation: 'Self',
    email: 'indira.gnanasekaran@example.com',
    profession: 'Tailor',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Gnanasekaran Pillai',
    emergencyContactPhone: '9865223052',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260051.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260051-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-051',
      registrationNumber: 'REG20260051',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Gynecology',
      consultant: 'Dr. Balasubramanian',
      createdAt: '2026-07-28T14:00:00.000Z',
    },
    createdAt: '2026-07-28T14:00:00.000Z',
  },
  {
    id: 'mock-052',
    uhid: 'NH20260052',
    title: 'Master',
    firstName: 'Vishal',
    lastName: 'Sathish',
    dateOfBirth: '2017-06-21',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '15, North Car Street',
    addressLine3: 'Sankarankovil',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627756',
    primaryPhone: '9884223052',
    primaryPhoneRelation: 'Mother',
    profession: 'School Student',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Sowmya Sathish',
    emergencyContactPhone: '9884223052',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-052',
      registrationNumber: 'REG20260052',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-28T14:45:00.000Z',
    },
    createdAt: '2026-07-28T14:45:00.000Z',
  },
  {
    id: 'mock-053',
    uhid: 'NH20260053',
    title: 'Mr',
    firstName: 'Alagesan',
    lastName: 'Ponnusamy',
    dateOfBirth: '1987-07-04',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '3, Main Bazaar',
    addressLine3: 'Alangulam',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627851',
    primaryPhone: '9843998053',
    primaryPhoneRelation: 'Self',
    profession: 'Farmer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Geetha Alagesan',
    emergencyContactPhone: '9843998054',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260053.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260053-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-053',
      registrationNumber: 'REG20260053',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-29T06:40:00.000Z',
    },
    createdAt: '2026-07-29T06:40:00.000Z',
  },
  {
    id: 'mock-054',
    uhid: 'NH20260054',
    title: 'Mrs',
    firstName: 'Geetha',
    lastName: 'Alagesan',
    dateOfBirth: '1991-02-28',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '3, Main Bazaar',
    addressLine3: 'Alangulam',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627851',
    primaryPhone: '9843998053',
    primaryPhoneRelation: 'Husband',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Alagesan Ponnusamy',
    emergencyContactPhone: '9843998053',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260054.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260054-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-054',
      registrationNumber: 'REG20260054',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'ENT',
      consultant: 'Dr. Lakshmi',
      createdAt: '2026-07-29T07:10:00.000Z',
    },
    createdAt: '2026-07-29T07:10:00.000Z',
  },
  {
    id: 'mock-055',
    uhid: 'NH20260055',
    title: 'Miss',
    firstName: 'Priyanka',
    lastName: 'Sekar',
    dateOfBirth: '2012-04-11',
    gender: 'Female',
    bloodGroup: 'BPositive',
    addressLine1: '12, Sekar Nagar',
    addressLine3: 'Alangulam',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    pincode: '627851',
    primaryPhone: '9600445055',
    primaryPhoneRelation: 'Father',
    profession: 'School Student',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Sekar Muthu',
    emergencyContactPhone: '9600445055',
    hasKnownAllergy: true,
    allergyType: 'Food - Seafood',
    allergySeverity: 'Moderate',
    currentRegistration: {
      id: 'mock-reg-055',
      registrationNumber: 'REG20260055',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Dermatology',
      consultant: 'Dr. Senthil Kumar',
      createdAt: '2026-07-29T07:45:00.000Z',
    },
    createdAt: '2026-07-29T07:45:00.000Z',
  },
  {
    id: 'mock-056',
    uhid: 'NH20260056',
    title: 'Mr',
    firstName: 'Ponraj',
    lastName: 'Muthiah',
    dateOfBirth: '1965-01-22',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '9, Kovil Street',
    addressLine3: 'Thisayanvilai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627657',
    primaryPhone: '9865889056',
    primaryPhoneRelation: 'Self',
    profession: 'Farmer',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Sanjay Kumar Muthiah',
    emergencyContactPhone: '9865889057',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260056.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260056-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-056',
      registrationNumber: 'REG20260056',
      encounterType: 'IP',
      modeOfArrival: 'Referred',
      department: 'Neurology',
      consultant: 'Dr. Priya',
      admissionType: 'NMLC',
      referralSource: 'Family recommendation — relative treated earlier at Nellai Hospitals',
      createdAt: '2026-07-29T08:20:00.000Z',
    },
    createdAt: '2026-07-29T08:20:00.000Z',
  },
  {
    id: 'mock-057',
    uhid: 'NH20260057',
    title: 'Mrs',
    firstName: 'Lalitha',
    lastName: 'Ponraj',
    dateOfBirth: '1970-06-06',
    gender: 'Female',
    bloodGroup: 'BPositive',
    addressLine1: '9, Kovil Street',
    addressLine3: 'Thisayanvilai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627657',
    primaryPhone: '9865889056',
    primaryPhoneRelation: 'Husband',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Ponraj Muthiah',
    emergencyContactPhone: '9865889056',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260057.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260057-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-057',
      registrationNumber: 'REG20260057',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      createdAt: '2026-07-29T09:05:00.000Z',
    },
    createdAt: '2026-07-29T09:05:00.000Z',
  },
  {
    id: 'mock-058',
    uhid: 'NH20260058',
    title: 'Mr',
    firstName: 'Sanjay',
    lastName: 'Kumar',
    dateOfBirth: '2000-03-19',
    gender: 'Male',
    bloodGroup: 'APositive',
    addressLine1: '17, Garage Street',
    addressLine3: 'Thisayanvilai',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627657',
    primaryPhone: '9500778058',
    primaryPhoneRelation: 'Self',
    email: 'sanjay.kumar@example.com',
    profession: 'Two-Wheeler Mechanic',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Ponraj Muthiah',
    emergencyContactPhone: '9865889056',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260058.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260058-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-058',
      registrationNumber: 'REG20260058',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Kumar',
      createdAt: '2026-07-29T09:50:00.000Z',
    },
    createdAt: '2026-07-29T09:50:00.000Z',
  },
  {
    id: 'mock-059',
    uhid: 'NH20260059',
    title: 'Mrs',
    firstName: 'Mahalakshmi',
    lastName: 'Devan',
    dateOfBirth: '1984-05-09',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '20, Coconut Grove Road',
    addressLine3: 'Radhapuram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627111',
    primaryPhone: '9944778059',
    primaryPhoneRelation: 'Self',
    profession: 'Coconut Farmer',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Devan Pillai',
    emergencyContactPhone: '9944778060',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260059.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260059-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-059',
      registrationNumber: 'REG20260059',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Gynecology',
      consultant: 'Dr. Balasubramanian',
      createdAt: '2026-07-29T10:30:00.000Z',
    },
    createdAt: '2026-07-29T10:30:00.000Z',
  },
  {
    id: 'mock-060',
    uhid: 'NH20260060',
    title: 'Mr',
    firstName: 'Udhaya Kumar',
    lastName: 'Raj',
    dateOfBirth: '1996-04-23',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '31, Market Road',
    addressLine3: 'Radhapuram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627111',
    primaryPhone: '9787334060',
    primaryPhoneRelation: 'Self',
    email: 'udhayakumar.raj@example.com',
    profession: 'Sales Executive',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Meera Raj',
    emergencyContactPhone: '9787334061',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260060.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260060-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-060',
      registrationNumber: 'REG20260060',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-29T11:15:00.000Z',
    },
    createdAt: '2026-07-29T11:15:00.000Z',
  },
  {
    id: 'mock-061',
    uhid: 'NH20260061',
    title: 'Baby',
    firstName: 'Raj',
    lastName: 'Meera',
    dateOfBirth: '2026-06-10',
    gender: 'Male',
    bloodGroup: 'Unknown',
    addressLine1: '31, Market Road',
    addressLine3: 'Radhapuram',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627111',
    primaryPhone: '9787334062',
    primaryPhoneRelation: 'Mother',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Meera Raj',
    emergencyContactPhone: '9787334062',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-061',
      registrationNumber: 'REG20260061',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Meenakshi',
      createdAt: '2026-07-29T11:40:00.000Z',
    },
    createdAt: '2026-07-29T11:40:00.000Z',
  },
  {
    id: 'mock-062',
    uhid: 'NH20260062',
    title: 'Mr',
    firstName: 'Velmurugan',
    lastName: 'Chinnasamy',
    dateOfBirth: '1977-02-14',
    gender: 'Male',
    bloodGroup: 'ABNegative',
    addressLine1: '5, Spice Market Street',
    addressLine3: 'Kadayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627415',
    primaryPhone: '9843556062',
    primaryPhoneRelation: 'Self',
    profession: 'Spice Trader',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Sudha Velmurugan',
    emergencyContactPhone: '9843556063',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-062',
      registrationNumber: 'REG20260062',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency',
      consultant: 'Dr. Karthikeyan',
      admissionType: 'MLC',
      createdAt: '2026-07-29T12:20:00.000Z',
    },
    createdAt: '2026-07-29T12:20:00.000Z',
  },
  {
    id: 'mock-063',
    uhid: 'NH20260063',
    title: 'Mrs',
    firstName: 'Sudha',
    lastName: 'Velmurugan',
    dateOfBirth: '1981-07-19',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '5, Spice Market Street',
    addressLine3: 'Kadayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627415',
    primaryPhone: '9843556062',
    primaryPhoneRelation: 'Husband',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Velmurugan Chinnasamy',
    emergencyContactPhone: '9843556062',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260063.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260063-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-063',
      registrationNumber: 'REG20260063',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Neurology',
      consultant: 'Dr. Priya',
      createdAt: '2026-07-29T13:00:00.000Z',
    },
    createdAt: '2026-07-29T13:00:00.000Z',
  },
  {
    id: 'mock-064',
    uhid: 'NH20260064',
    title: 'Ms',
    firstName: 'Nithya',
    lastName: 'Sekaran',
    dateOfBirth: '2005-06-08',
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '14, New Bus Stand Road',
    addressLine3: 'Kadayam',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627415',
    primaryPhone: '9600223064',
    primaryPhoneRelation: 'Self',
    email: 'nithya.sekaran@example.com',
    profession: 'Beautician',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Pushpa Sekaran',
    emergencyContactPhone: '9600223065',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260064.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260064-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-064',
      registrationNumber: 'REG20260064',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'ENT',
      consultant: 'Dr. Lakshmi',
      createdAt: '2026-07-29T13:40:00.000Z',
    },
    createdAt: '2026-07-29T13:40:00.000Z',
  },
  {
    id: 'mock-065',
    uhid: 'NH20260065',
    title: 'Mr',
    firstName: 'Anandan',
    lastName: 'Muthu',
    dateOfBirth: '1973-03-27',
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '2, Estate Road',
    addressLine3: 'Kalakkad',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627501',
    primaryPhone: '9865334065',
    primaryPhoneRelation: 'Self',
    profession: 'Rubber Estate Supervisor',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Rani Anandan',
    emergencyContactPhone: '9865334066',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260065.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260065-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-065',
      registrationNumber: 'REG20260065',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Kumar',
      admissionType: 'NMLC',
      createdAt: '2026-07-29T14:15:00.000Z',
    },
    createdAt: '2026-07-29T14:15:00.000Z',
  },
  {
    id: 'mock-066',
    uhid: 'NH20260066',
    title: 'Mrs',
    firstName: 'Rani',
    lastName: 'Sivan',
    dateOfBirth: '1958-04-14',
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '9, Foothills Road',
    addressLine3: 'Kalakkad',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627501',
    primaryPhone: '9787889066',
    primaryPhoneRelation: 'Self',
    profession: 'Retired Teacher',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Vidya Sivan',
    emergencyContactPhone: '9787889067',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260066.jpg',
    idProofType: 'VoterId',
    idProofPath: '/uploads/patients/id-proofs/NH20260066-voterid.pdf',
    currentRegistration: {
      id: 'mock-reg-066',
      registrationNumber: 'REG20260066',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Revathi',
      createdAt: '2026-07-29T14:50:00.000Z',
    },
    createdAt: '2026-07-29T14:50:00.000Z',
  },
  {
    id: 'mock-067',
    uhid: 'NH20260067',
    title: 'Mr',
    firstName: 'Charles',
    lastName: 'David',
    dateOfBirth: '1990-05-30',
    gender: 'Male',
    bloodGroup: 'ONegative',
    addressLine1: '16, Church Road',
    addressLine3: 'Kalakkad',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627501',
    primaryPhone: '9942667067',
    primaryPhoneRelation: 'Self',
    email: 'charles.david@example.com',
    profession: 'Hotel Owner',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Mary Charles',
    emergencyContactPhone: '9942667068',
    hasKnownAllergy: true,
    allergyType: 'Food - Egg',
    allergySeverity: 'Mild',
    photoPath: '/uploads/patients/photos/NH20260067.jpg',
    idProofType: 'DrivingLicense',
    idProofPath: '/uploads/patients/id-proofs/NH20260067-dl.pdf',
    currentRegistration: {
      id: 'mock-reg-067',
      registrationNumber: 'REG20260067',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Arun Kumar',
      createdAt: '2026-07-29T15:30:00.000Z',
    },
    createdAt: '2026-07-29T15:30:00.000Z',
  },
  {
    id: 'mock-068',
    uhid: 'NH20260068',
    title: 'Mr',
    firstName: 'Karthikeyan',
    lastName: 'Doss',
    dateOfBirth: '1980-06-22',
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '48, Vannarpettai',
    addressLine3: 'Tirunelveli Town',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    pincode: '627001',
    primaryPhone: '9865223068',
    primaryPhoneRelation: 'Self',
    email: 'karthikeyan.doss@example.com',
    profession: 'Weaving Mill Supervisor',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Uma Doss',
    emergencyContactPhone: '9865223069',
    hasKnownAllergy: false,
    photoPath: '/uploads/patients/photos/NH20260068.jpg',
    idProofType: 'Aadhaar',
    idProofPath: '/uploads/patients/id-proofs/NH20260068-aadhaar.pdf',
    currentRegistration: {
      id: 'mock-reg-068',
      registrationNumber: 'REG20260068',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'General Medicine',
      consultant: 'Dr. Karthikeyan',
      createdAt: '2026-07-29T16:10:00.000Z',
    },
    createdAt: '2026-07-29T16:10:00.000Z',
  },
];

export const MOCK_PATIENTS: Patient[] = PATIENT_SEEDS.map((seed) => ({ ...seed, age: calculateAge(seed.dateOfBirth) }));
