import type { Patient } from '@hms/shared';

/**
 * Seed data for the demo/offline fallback (see mockPatientsStore.ts) — lets the Patient
 * Management UI be demoed for client sign-off before the backend is wired up. Not used
 * once the API is reachable.
 */
export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'mock-001',
    uhid: 'LH20260001',
    title: 'Mr',
    firstName: 'Arjun',
    lastName: 'Menon',
    dateOfBirth: '1988-04-12',
    age: 38,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '12, Marine Drive Apartments',
    addressLine2: 'MG Road',
    addressLine3: 'Kochi',
    district: 'Ernakulam',
    state: 'Kerala',
    pincode: '682031',
    primaryPhone: '9847012345',
    primaryPhoneRelation: 'Self',
    email: 'arjun.menon@example.com',
    profession: 'Software Engineer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Divya Menon',
    emergencyContactPhone: '9847012346',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-001',
      registrationNumber: 'REG20260001',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Cardiology',
      consultant: 'Dr. Priya Nair',
      createdAt: '2026-07-20T09:15:00.000Z',
    },
    createdAt: '2026-07-20T09:15:00.000Z',
  },
  {
    id: 'mock-002',
    uhid: 'LH20260002',
    title: 'Mrs',
    firstName: 'Lakshmi',
    lastName: 'Iyer',
    dateOfBirth: '1975-11-02',
    age: 50,
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '45, Gandhi Nagar',
    addressLine3: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600020',
    primaryPhone: '9884023456',
    primaryPhoneRelation: 'Self',
    email: 'lakshmi.iyer@example.com',
    profession: 'Teacher',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Karthik Iyer',
    emergencyContactPhone: '9884023457',
    hasKnownAllergy: true,
    allergyType: 'Drug - Penicillin',
    allergySeverity: 'Moderate',
    currentRegistration: {
      id: 'mock-reg-002',
      registrationNumber: 'REG20260002',
      encounterType: 'IP',
      modeOfArrival: 'Ambulance',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Babu',
      admissionType: 'NMLC',
      createdAt: '2026-07-21T11:40:00.000Z',
    },
    createdAt: '2026-07-21T11:40:00.000Z',
  },
  {
    id: 'mock-003',
    uhid: 'LH20260003',
    title: 'Master',
    firstName: 'Aarav',
    lastName: 'Sharma',
    dateOfBirth: '2018-02-19',
    age: 8,
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '7, Sector 21',
    addressLine3: 'Noida',
    district: 'Gautam Buddh Nagar',
    state: 'Uttar Pradesh',
    pincode: '201301',
    primaryPhone: '9911034567',
    primaryPhoneRelation: 'Father',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Rohit Sharma',
    emergencyContactPhone: '9911034567',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-003',
      registrationNumber: 'REG20260003',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Anjali Rao',
      createdAt: '2026-07-21T14:05:00.000Z',
    },
    createdAt: '2026-07-21T14:05:00.000Z',
  },
  {
    id: 'mock-004',
    uhid: 'LH20260004',
    title: 'Ms',
    firstName: 'Fatima',
    lastName: 'Khan',
    dateOfBirth: '1996-07-30',
    age: 29,
    gender: 'Female',
    bloodGroup: 'ABPositive',
    addressLine1: '18, Park Circus',
    addressLine3: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700017',
    primaryPhone: '9830045678',
    primaryPhoneRelation: 'Self',
    email: 'fatima.khan@example.com',
    profession: 'Graphic Designer',
    emergencyContactRelationship: 'Sister',
    emergencyContactName: 'Ayesha Khan',
    emergencyContactPhone: '9830045679',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-004',
      registrationNumber: 'REG20260004',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency Medicine',
      consultant: 'Dr. Vivek Chatterjee',
      admissionType: 'MLC',
      createdAt: '2026-07-22T02:50:00.000Z',
    },
    createdAt: '2026-07-22T02:50:00.000Z',
  },
  {
    id: 'mock-005',
    uhid: 'LH20260005',
    title: 'Mr',
    firstName: 'Rohan',
    lastName: 'Deshmukh',
    dateOfBirth: '1982-09-14',
    age: 43,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '23, Kothrud',
    addressLine3: 'Pune',
    district: 'Pune',
    state: 'Maharashtra',
    pincode: '411038',
    primaryPhone: '9822056789',
    primaryPhoneRelation: 'Self',
    email: 'rohan.deshmukh@example.com',
    profession: 'Business Owner',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Sneha Deshmukh',
    emergencyContactPhone: '9822056790',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-005',
      registrationNumber: 'REG20260005',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Manoj Kulkarni',
      createdAt: '2026-07-22T08:30:00.000Z',
    },
    createdAt: '2026-07-22T08:30:00.000Z',
  },
  {
    id: 'mock-006',
    uhid: 'LH20260006',
    title: 'Mrs',
    firstName: 'Priya',
    lastName: 'Reddy',
    dateOfBirth: '1990-01-25',
    age: 36,
    gender: 'Female',
    bloodGroup: 'BNegative',
    addressLine1: '56, Banjara Hills',
    addressLine3: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    pincode: '500034',
    primaryPhone: '9866067890',
    primaryPhoneRelation: 'Self',
    email: 'priya.reddy@example.com',
    profession: 'Architect',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Kiran Reddy',
    emergencyContactPhone: '9866067891',
    hasKnownAllergy: true,
    allergyType: 'Food - Peanuts',
    allergySeverity: 'Severe',
    currentRegistration: {
      id: 'mock-reg-006',
      registrationNumber: 'REG20260006',
      encounterType: 'OP',
      modeOfArrival: 'Referred',
      department: 'Dermatology',
      consultant: 'Dr. Neha Verma',
      referralSource: 'Dr. Ramesh Rao — City Clinic',
      createdAt: '2026-07-22T12:10:00.000Z',
    },
    createdAt: '2026-07-22T12:10:00.000Z',
  },
  {
    id: 'mock-007',
    uhid: 'LH20260007',
    title: 'Mr',
    firstName: 'Vikram',
    lastName: 'Singh',
    dateOfBirth: '1965-06-08',
    age: 61,
    gender: 'Male',
    bloodGroup: 'APositive',
    addressLine1: '9, Civil Lines',
    addressLine3: 'Jaipur',
    district: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302006',
    primaryPhone: '9414078901',
    primaryPhoneRelation: 'Self',
    profession: 'Retired Government Officer',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Ritu Singh',
    emergencyContactPhone: '9414078902',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-007',
      registrationNumber: 'REG20260007',
      encounterType: 'IP',
      modeOfArrival: 'WalkIn',
      department: 'Nephrology',
      consultant: 'Dr. Ashok Gehlot',
      admissionType: 'NMLC',
      createdAt: '2026-07-23T07:20:00.000Z',
    },
    createdAt: '2026-07-23T07:20:00.000Z',
  },
  {
    id: 'mock-008',
    uhid: 'LH20260008',
    title: 'Miss',
    firstName: 'Ananya',
    lastName: 'Bose',
    dateOfBirth: '2001-03-17',
    age: 25,
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '31, Salt Lake',
    addressLine3: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700064',
    primaryPhone: '9831089012',
    primaryPhoneRelation: 'Self',
    email: 'ananya.bose@example.com',
    profession: 'Student',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Mitali Bose',
    emergencyContactPhone: '9831089013',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-008',
      registrationNumber: 'REG20260008',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Ophthalmology',
      consultant: 'Dr. Rajesh Sen',
      createdAt: '2026-07-23T10:45:00.000Z',
    },
    createdAt: '2026-07-23T10:45:00.000Z',
  },
  {
    id: 'mock-009',
    uhid: 'LH20260009',
    title: 'Mr',
    firstName: 'Suresh',
    lastName: 'Pillai',
    dateOfBirth: '1979-12-05',
    age: 46,
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '4, Vellayambalam',
    addressLine3: 'Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    state: 'Kerala',
    pincode: '695010',
    primaryPhone: '9847090123',
    primaryPhoneRelation: 'Self',
    email: 'suresh.pillai@example.com',
    profession: 'Bank Manager',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Meera Pillai',
    emergencyContactPhone: '9847090124',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-009',
      registrationNumber: 'REG20260009',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Cardiology',
      consultant: 'Dr. Priya Nair',
      admissionType: 'MLC',
      createdAt: '2026-07-23T19:55:00.000Z',
    },
    createdAt: '2026-07-23T19:55:00.000Z',
  },
  {
    id: 'mock-010',
    uhid: 'LH20260010',
    title: 'Mrs',
    firstName: 'Kavita',
    lastName: 'Joshi',
    dateOfBirth: '1985-05-22',
    age: 41,
    gender: 'Female',
    bloodGroup: 'ABNegative',
    addressLine1: '67, Vastrapur',
    addressLine3: 'Ahmedabad',
    district: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380015',
    primaryPhone: '9825001234',
    primaryPhoneRelation: 'Self',
    email: 'kavita.joshi@example.com',
    profession: 'Homemaker',
    emergencyContactRelationship: 'Husband',
    emergencyContactName: 'Nitin Joshi',
    emergencyContactPhone: '9825001235',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-010',
      registrationNumber: 'REG20260010',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Gynecology',
      consultant: 'Dr. Sunita Shah',
      createdAt: '2026-07-24T06:30:00.000Z',
    },
    createdAt: '2026-07-24T06:30:00.000Z',
  },
  {
    id: 'mock-011',
    uhid: 'LH20260011',
    title: 'Baby',
    firstName: 'Ishaan',
    lastName: 'Verma',
    dateOfBirth: '2025-12-01',
    age: 0,
    gender: 'Male',
    bloodGroup: 'Unknown',
    addressLine1: '14, Rohini Sector 9',
    addressLine3: 'New Delhi',
    district: 'North West Delhi',
    state: 'Delhi',
    pincode: '110085',
    primaryPhone: '9871012345',
    primaryPhoneRelation: 'Mother',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Pooja Verma',
    emergencyContactPhone: '9871012345',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-011',
      registrationNumber: 'REG20260011',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Pediatrics',
      consultant: 'Dr. Anjali Rao',
      createdAt: '2026-07-24T09:10:00.000Z',
    },
    createdAt: '2026-07-24T09:10:00.000Z',
  },
  {
    id: 'mock-012',
    uhid: 'LH20260012',
    title: 'Mr',
    firstName: 'Aditya',
    lastName: 'Kulkarni',
    dateOfBirth: '1993-08-19',
    age: 32,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '88, Viman Nagar',
    addressLine3: 'Pune',
    district: 'Pune',
    state: 'Maharashtra',
    pincode: '411014',
    primaryPhone: '9822023456',
    primaryPhoneRelation: 'Self',
    email: 'aditya.kulkarni@example.com',
    profession: 'Marketing Manager',
    emergencyContactRelationship: 'Brother',
    emergencyContactName: 'Sagar Kulkarni',
    emergencyContactPhone: '9822023457',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-012',
      registrationNumber: 'REG20260012',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'ENT',
      consultant: 'Dr. Farhan Ali',
      createdAt: '2026-07-24T13:25:00.000Z',
    },
    createdAt: '2026-07-24T13:25:00.000Z',
  },
  {
    id: 'mock-013',
    uhid: 'LH20260013',
    title: 'Ms',
    firstName: 'Sneha',
    lastName: 'Nair',
    dateOfBirth: '1998-10-11',
    age: 27,
    gender: 'Female',
    bloodGroup: 'APositive',
    addressLine1: '3, Panampilly Nagar',
    addressLine3: 'Kochi',
    district: 'Ernakulam',
    state: 'Kerala',
    pincode: '682036',
    primaryPhone: '9847045678',
    primaryPhoneRelation: 'Self',
    email: 'sneha.nair@example.com',
    profession: 'Nurse',
    emergencyContactRelationship: 'Mother',
    emergencyContactName: 'Radha Nair',
    emergencyContactPhone: '9847045679',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-013',
      registrationNumber: 'REG20260013',
      encounterType: 'DayCare',
      modeOfArrival: 'WalkIn',
      department: 'General Surgery',
      consultant: 'Dr. Manoj Kulkarni',
      createdAt: '2026-07-25T05:40:00.000Z',
    },
    createdAt: '2026-07-25T05:40:00.000Z',
  },
  {
    id: 'mock-014',
    uhid: 'LH20260014',
    title: 'Mr',
    firstName: 'Rajesh',
    lastName: 'Gupta',
    dateOfBirth: '1970-02-28',
    age: 56,
    gender: 'Male',
    bloodGroup: 'BPositive',
    addressLine1: '21, Model Town',
    addressLine3: 'Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141002',
    primaryPhone: '9815056789',
    primaryPhoneRelation: 'Self',
    profession: 'Shop Owner',
    emergencyContactRelationship: 'Son',
    emergencyContactName: 'Amit Gupta',
    emergencyContactPhone: '9815056790',
    hasKnownAllergy: true,
    allergyType: 'Drug - Sulfa',
    allergySeverity: 'Mild',
    currentRegistration: {
      id: 'mock-reg-014',
      registrationNumber: 'REG20260014',
      encounterType: 'IP',
      modeOfArrival: 'Referred',
      department: 'Gastroenterology',
      consultant: 'Dr. Harpreet Singh',
      admissionType: 'NMLC',
      referralSource: 'Dr. Baljeet Kaur — Family Clinic',
      createdAt: '2026-07-25T10:15:00.000Z',
    },
    createdAt: '2026-07-25T10:15:00.000Z',
  },
  {
    id: 'mock-015',
    uhid: 'LH20260015',
    title: 'Mrs',
    firstName: 'Meenakshi',
    lastName: 'Subramaniam',
    dateOfBirth: '1958-09-09',
    age: 67,
    gender: 'Female',
    bloodGroup: 'OPositive',
    addressLine1: '9, T Nagar',
    addressLine3: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600017',
    primaryPhone: '9884001234',
    primaryPhoneRelation: 'Self',
    profession: 'Retired',
    emergencyContactRelationship: 'Daughter',
    emergencyContactName: 'Divya Subramaniam',
    emergencyContactPhone: '9884001235',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-015',
      registrationNumber: 'REG20260015',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Ophthalmology',
      consultant: 'Dr. Rajesh Sen',
      createdAt: '2026-07-25T14:50:00.000Z',
    },
    createdAt: '2026-07-25T14:50:00.000Z',
  },
  {
    id: 'mock-016',
    uhid: 'LH20260016',
    title: 'Mr',
    firstName: 'Farhan',
    lastName: 'Sheikh',
    dateOfBirth: '1991-04-04',
    age: 35,
    gender: 'Male',
    bloodGroup: 'ABPositive',
    addressLine1: '55, Andheri West',
    addressLine3: 'Mumbai',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    pincode: '400058',
    primaryPhone: '9821067890',
    primaryPhoneRelation: 'Self',
    email: 'farhan.sheikh@example.com',
    profession: 'Chartered Accountant',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Zara Sheikh',
    emergencyContactPhone: '9821067891',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-016',
      registrationNumber: 'REG20260016',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Orthopedics',
      consultant: 'Dr. Suresh Babu',
      createdAt: '2026-07-25T20:05:00.000Z',
    },
    createdAt: '2026-07-25T20:05:00.000Z',
  },
  {
    id: 'mock-017',
    uhid: 'LH20260017',
    title: 'Ms',
    firstName: 'Neha',
    lastName: 'Agarwal',
    dateOfBirth: '1994-06-16',
    age: 32,
    gender: 'Female',
    bloodGroup: 'BNegative',
    addressLine1: '10, Civil Lines',
    addressLine3: 'Kanpur',
    district: 'Kanpur Nagar',
    state: 'Uttar Pradesh',
    pincode: '208001',
    primaryPhone: '9935078901',
    primaryPhoneRelation: 'Self',
    email: 'neha.agarwal@example.com',
    profession: 'Lawyer',
    emergencyContactRelationship: 'Father',
    emergencyContactName: 'Mahesh Agarwal',
    emergencyContactPhone: '9935078902',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-017',
      registrationNumber: 'REG20260017',
      encounterType: 'OP',
      modeOfArrival: 'WalkIn',
      department: 'Dermatology',
      consultant: 'Dr. Neha Verma',
      createdAt: '2026-07-26T04:15:00.000Z',
    },
    createdAt: '2026-07-26T04:15:00.000Z',
  },
  {
    id: 'mock-018',
    uhid: 'LH20260018',
    title: 'Mr',
    firstName: 'Deepak',
    lastName: 'Chauhan',
    dateOfBirth: '1987-01-30',
    age: 39,
    gender: 'Male',
    bloodGroup: 'OPositive',
    addressLine1: '33, Malviya Nagar',
    addressLine3: 'Jaipur',
    district: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302017',
    primaryPhone: '9414089012',
    primaryPhoneRelation: 'Self',
    email: 'deepak.chauhan@example.com',
    profession: 'Civil Engineer',
    emergencyContactRelationship: 'Wife',
    emergencyContactName: 'Rekha Chauhan',
    emergencyContactPhone: '9414089013',
    hasKnownAllergy: false,
    currentRegistration: {
      id: 'mock-reg-018',
      registrationNumber: 'REG20260018',
      encounterType: 'Emergency',
      modeOfArrival: 'Ambulance',
      department: 'Emergency Medicine',
      consultant: 'Dr. Vivek Chatterjee',
      admissionType: 'MLC',
      createdAt: '2026-07-26T06:30:00.000Z',
    },
    createdAt: '2026-07-26T06:30:00.000Z',
  },
];
