import type { Product } from '@hms/shared';

/**
 * Seed rows for the offline mock fallback (see mockProductsStore.ts) — reference ids match
 * the Masters offline mock seed (features/masters/configs/*.ts), so labels resolve
 * correctly even when both modules are running against the fallback simultaneously.
 */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-product-001',
    sku: 'SKU-PARA500',
    productCode: 'PHARM-PARA500',
    productName: 'Paracetamol 500mg',
    genericName: 'Paracetamol',
    description: 'Analgesic/antipyretic tablet, strip of 10.',
    brandId: 'brand-001',
    manufacturerId: 'manufacturer-001',
    categoryId: 'product-category-001',
    subCategoryId: 'product-sub-category-001',
    groupId: 'product-group-001',
    uomId: 'uom-002',
    baseUomId: 'uom-001',
    isBatchTracked: true,
    isSerialized: false,
    isActive: true,
    reorderLevel: 50,
    minStockLevel: 20,
    maxStockLevel: 500,
    mrp: 25,
    costPrice: 12,
    sellingPrice: 20,
    hsnCode: '3004',
    weight: null,
    volume: null,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: null,
  },
  {
    id: 'mock-product-002',
    sku: 'SKU-GLOVES-M',
    productCode: 'CONSUM-GLOVES-M',
    productName: 'Nitrile Examination Gloves (Medium)',
    genericName: null,
    description: 'Powder-free nitrile gloves, box of 100.',
    brandId: 'brand-003',
    manufacturerId: 'manufacturer-002',
    categoryId: 'product-category-002',
    subCategoryId: 'product-sub-category-003',
    groupId: 'product-group-003',
    uomId: 'uom-003',
    baseUomId: 'uom-001',
    isBatchTracked: false,
    isSerialized: false,
    isActive: true,
    reorderLevel: 30,
    minStockLevel: 10,
    maxStockLevel: 200,
    mrp: 450,
    costPrice: 280,
    sellingPrice: 400,
    hsnCode: '4015',
    weight: null,
    volume: null,
    createdAt: '2026-01-02T00:00:00.000Z',
    updatedAt: null,
  },
];
