import type { ModulePermissions, Role } from './types';

function perm(view: boolean, create = view, edit = view, del = view): ModulePermissions {
  return { view, create, edit, delete: del };
}

const NONE = perm(false, false, false, false);
const FULL = perm(true, true, true, true);
const VIEW_ONLY = perm(true, false, false, false);

/** Seed data for the offline Roles Management demo (see mockRolesStore.ts) — this module has no backend yet, so this is the only source of data. */
export const MOCK_ROLES: Role[] = [
  {
    id: 'role-001',
    name: 'Super Admin',
    description: 'Unrestricted access to every module, including system configuration.',
    status: 'Active',
    permissions: {
      'patient-management': FULL,
      'clinical-care': FULL,
      diagnostics: FULL,
      pharmacy: FULL,
      'support-services': FULL,
      'finance-billing': FULL,
      'records-compliance': FULL,
      'workforce-admin': FULL,
      engagement: FULL,
      'reports-analytics': FULL,
    },
    createdAt: '2026-01-10T09:00:00.000Z',
    updatedAt: '2026-06-02T11:20:00.000Z',
  },
  {
    id: 'role-002',
    name: 'Doctor',
    description: 'Clinical consultation, prescriptions, and diagnostic order access.',
    status: 'Active',
    permissions: {
      'patient-management': perm(true, false, true, false),
      'clinical-care': FULL,
      diagnostics: perm(true, true, true, false),
      pharmacy: perm(true, true, false, false),
      'support-services': NONE,
      'finance-billing': VIEW_ONLY,
      'records-compliance': perm(true, false, true, false),
      'workforce-admin': NONE,
      engagement: VIEW_ONLY,
      'reports-analytics': VIEW_ONLY,
    },
    createdAt: '2026-01-12T09:00:00.000Z',
    updatedAt: '2026-07-01T15:40:00.000Z',
  },
  {
    id: 'role-003',
    name: 'Nurse',
    description: 'Ward charting, patient vitals, and medication administration.',
    status: 'Active',
    permissions: {
      'patient-management': perm(true, false, true, false),
      'clinical-care': perm(true, true, true, false),
      diagnostics: VIEW_ONLY,
      pharmacy: perm(true, true, false, false),
      'support-services': NONE,
      'finance-billing': NONE,
      'records-compliance': VIEW_ONLY,
      'workforce-admin': NONE,
      engagement: VIEW_ONLY,
      'reports-analytics': NONE,
    },
    createdAt: '2026-01-15T09:00:00.000Z',
    updatedAt: '2026-06-18T10:05:00.000Z',
  },
  {
    id: 'role-004',
    name: 'Receptionist',
    description: 'Patient registration, appointment scheduling, and front-desk billing.',
    status: 'Active',
    permissions: {
      'patient-management': FULL,
      'clinical-care': NONE,
      diagnostics: NONE,
      pharmacy: NONE,
      'support-services': NONE,
      'finance-billing': perm(true, true, false, false),
      'records-compliance': VIEW_ONLY,
      'workforce-admin': NONE,
      engagement: perm(true, true, false, false),
      'reports-analytics': NONE,
    },
    createdAt: '2026-01-18T09:00:00.000Z',
    updatedAt: '2026-05-22T13:30:00.000Z',
  },
  {
    id: 'role-005',
    name: 'Pharmacist',
    description: 'Prescription fulfillment, drug master, and stock/batch tracking.',
    status: 'Active',
    permissions: {
      'patient-management': VIEW_ONLY,
      'clinical-care': VIEW_ONLY,
      diagnostics: NONE,
      pharmacy: FULL,
      'support-services': perm(true, true, false, false),
      'finance-billing': VIEW_ONLY,
      'records-compliance': NONE,
      'workforce-admin': NONE,
      engagement: NONE,
      'reports-analytics': NONE,
    },
    createdAt: '2026-02-02T09:00:00.000Z',
    updatedAt: '2026-06-29T08:50:00.000Z',
  },
  {
    id: 'role-006',
    name: 'Lab Technician',
    description: 'Sample tracking, test order queue, and result entry.',
    status: 'Active',
    permissions: {
      'patient-management': VIEW_ONLY,
      'clinical-care': NONE,
      diagnostics: perm(true, true, true, false),
      pharmacy: NONE,
      'support-services': NONE,
      'finance-billing': NONE,
      'records-compliance': NONE,
      'workforce-admin': NONE,
      engagement: NONE,
      'reports-analytics': NONE,
    },
    createdAt: '2026-02-10T09:00:00.000Z',
    updatedAt: '2026-04-11T09:15:00.000Z',
  },
  {
    id: 'role-007',
    name: 'Accountant',
    description: 'Invoice ledger, payments, insurance claims, and financial reporting.',
    status: 'Active',
    permissions: {
      'patient-management': NONE,
      'clinical-care': NONE,
      diagnostics: NONE,
      pharmacy: NONE,
      'support-services': VIEW_ONLY,
      'finance-billing': FULL,
      'records-compliance': NONE,
      'workforce-admin': NONE,
      engagement: NONE,
      'reports-analytics': perm(true, true, false, false),
    },
    createdAt: '2026-02-14T09:00:00.000Z',
    updatedAt: '2026-07-05T16:00:00.000Z',
  },
  {
    id: 'role-008',
    name: 'HR Manager',
    description: 'Staff directory, roster/shift assignment, and leave management.',
    status: 'Inactive',
    permissions: {
      'patient-management': NONE,
      'clinical-care': NONE,
      diagnostics: NONE,
      pharmacy: NONE,
      'support-services': NONE,
      'finance-billing': NONE,
      'records-compliance': NONE,
      'workforce-admin': FULL,
      engagement: perm(true, true, true, false),
      'reports-analytics': VIEW_ONLY,
    },
    createdAt: '2026-03-01T09:00:00.000Z',
    updatedAt: '2026-05-30T12:10:00.000Z',
  },
  {
    id: 'role-009',
    name: 'Front Desk (Trainee)',
    description: 'Limited, view-only access used while shadowing during onboarding.',
    status: 'Inactive',
    permissions: {
      'patient-management': VIEW_ONLY,
      'clinical-care': NONE,
      diagnostics: NONE,
      pharmacy: NONE,
      'support-services': NONE,
      'finance-billing': NONE,
      'records-compliance': NONE,
      'workforce-admin': NONE,
      engagement: NONE,
      'reports-analytics': NONE,
    },
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-04-20T09:00:00.000Z',
  },
];
