<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\HMS.Modules.Identity\HMS.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Patients\HMS.Modules.Patients\HMS.Modules.Patients.csproj" />
    <ProjectReference Include="..\..\src\Modules\Documents\HMS.Modules.Documents\HMS.Modules.Documents.csproj" />
    <ProjectReference Include="..\..\src\Modules\Appointments\HMS.Modules.Appointments\HMS.Modules.Appointments.csproj" />
    <ProjectReference Include="..\..\src\Modules\Staff\HMS.Modules.Staff\HMS.Modules.Staff.csproj" />
    <ProjectReference Include="..\..\src\Modules\Billing\HMS.Modules.Billing\HMS.Modules.Billing.csproj" />
    <ProjectReference Include="..\..\src\Modules\Notifications\HMS.Modules.Notifications\HMS.Modules.Notifications.csproj" />
    <ProjectReference Include="..\..\src\Shared\HMS.Shared.Kernel\HMS.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Shared\HMS.Shared.Infrastructure\HMS.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Masters\HMS.Modules.Masters\HMS.Modules.Masters.csproj" />
    <ProjectReference Include="..\..\src\Modules\Products\HMS.Modules.Products\HMS.Modules.Products.csproj" />
    <ProjectReference Include="..\..\src\Modules\HR\HMS.Modules.HR\HMS.Modules.HR.csproj" />
    <ProjectReference Include="..\..\src\Modules\Calendar\HMS.Modules.Calendar\HMS.Modules.Calendar.csproj" />
    <ProjectReference Include="..\..\src\Modules\IPD\HMS.Modules.IPD\HMS.Modules.IPD.csproj" />
  </ItemGroup>

</Project>
