// <auto-generated />
using System;
using HMS.Modules.DischargeSummary.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HMS.Database.Migrations.DischargeSummary.Migrations
{
    [DbContext(typeof(DischargeSummaryDbContext))]
    [Migration("20260908103507_AddDischargeSummaryClinicalFields")]
    partial class AddDischargeSummaryClinicalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discharge_summary")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HMS.Modules.DischargeSummary.Domain.DischargeSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activity")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("activity");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_id");

                    b.Property<string>("Anaesthesia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("anaesthesia");

                    b.Property<string>("Anaesthetist")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("anaesthetist");

                    b.Property<string>("AssistantSurgeons")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("assistant_surgeons");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<Guid?>("CheckedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_by_user_id");

                    b.Property<string>("ChiefComplaints")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("chief_complaints");

                    b.Property<string>("CnsFindings")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cns_findings");

                    b.Property<string>("ConditionAtDischarge")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("condition_at_discharge");

                    b.Property<Guid?>("ConsultantApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultant_approved_by_user_id");

                    b.Property<string>("CourseInHospital")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("course_in_hospital");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CvsFindings")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cvs_findings");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Diet")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("diet");

                    b.Property<string>("EmergencyInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("emergency_instructions");

                    b.Property<string>("FamilyHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("family_history");

                    b.Property<string>("FinalDiagnosis")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("final_diagnosis");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<Guid?>("FinalizedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("finalized_by_user_id");

                    b.Property<string>("Gait")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("gait");

                    b.Property<string>("GeneralExamination")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("general_examination");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("HistoryOfPresentingIllness")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("history_of_presenting_illness");

                    b.Property<string>("IntraOperativeFindings")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("intra_operative_findings");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LocalExamination")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("local_examination");

                    b.Property<string>("OperativeNotes")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("operative_notes");

                    b.Property<string>("PaFindings")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("pa_findings");

                    b.Property<string>("PastMedicalHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("past_medical_history");

                    b.Property<string>("PastSurgicalHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("past_surgical_history");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PersonalHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("personal_history");

                    b.Property<string>("Physiotherapy")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("physiotherapy");

                    b.Property<Guid?>("PreparedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("prepared_by_user_id");

                    b.Property<string>("PrimarySurgeon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("primary_surgeon");

                    b.Property<DateTime?>("ProcedureDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procedure_date_time");

                    b.Property<string>("ProcedureName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("procedure_name");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("integer")
                        .HasColumnName("pulse_rate");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<string>("ReviewInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_instructions");

                    b.Property<string>("RsFindings")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rs_findings");

                    b.Property<int?>("SpO2Percent")
                        .HasColumnType("integer")
                        .HasColumnName("spo2_percent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SurgicalPosition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("surgical_position");

                    b.Property<decimal?>("TemperatureF")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_f");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.Property<string>("WoundCare")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("wound_care");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_discharge_summaries");

                    b.HasIndex("AdmissionId")
                        .IsUnique()
                        .HasDatabaseName("ux_discharge_summaries_admission_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_discharge_summaries_patient_id");

                    b.ToTable("discharge_summaries", "discharge_summary");
                });
#pragma warning restore 612, 618
        }
    }
}
