using HMS.Modules.IPD.Contracts;
using HMS.Shared.Kernel;

namespace HMS.Modules.IPD.Domain;

/// <summary>
/// An inpatient stay — converts an existing Patients-module patient into an admitted
/// inpatient occupying a specific Ward/Bed. PatientId/DepartmentId/ConsultantId reference
/// Patients/Masters respectively; WardId/BedId reference this module's own Ward/Bed
/// aggregates. Bed occupancy side effects (Available/Occupied) are orchestrated by
/// AdmissionService, not by this entity, since they mutate a different aggregate (Bed).
/// WardId/BedId are nullable to accommodate <see cref="CreateRequest"/> — a Requested
/// admission raised from OPD before any ward/bed has actually been chosen (see AssignBed).
/// Every row created via the original <see cref="Create"/> factory still gets both set
/// immediately, exactly as before.
/// </summary>
internal class Admission : Entity
{
    public string AdmissionNumber { get; private set; } = null!;
    public Guid PatientId { get; private set; }
    public Guid DepartmentId { get; private set; }
    public Guid ConsultantId { get; private set; }
    public Guid? WardId { get; private set; }
    public Guid? BedId { get; private set; }
    public DateTime AdmissionDateTime { get; private set; }
    public AdmissionType AdmissionType { get; private set; }
    public string ReasonForAdmission { get; private set; } = null!;
    public AdmissionStatus Status { get; private set; }

    public DateTime? DischargeDateTime { get; private set; }
    public DischargeType? DischargeType { get; private set; }
    public string? FinalDiagnosis { get; private set; }
    public string? DischargeNotes { get; private set; }
    public string? FollowUpAdvice { get; private set; }

    /// <summary>App-level reference to HMS.Modules.Billing.Invoice, no DB FK — set once
    /// IPDBillingService.GenerateFinalBillAsync succeeds. Null means no final bill has been
    /// generated yet (only possible once Discharged) — see ADR-066.</summary>
    public Guid? FinalInvoiceId { get; private set; }

    // Required by EF Core materialization.
    private Admission()
    {
    }

    private Admission(
        Guid id,
        string admissionNumber,
        Guid patientId,
        Guid departmentId,
        Guid consultantId,
        Guid? wardId,
        Guid? bedId,
        DateTime admissionDateTime,
        AdmissionType admissionType,
        string reasonForAdmission,
        AdmissionStatus initialStatus,
        Guid? createdBy)
        : base(id, createdBy)
    {
        AdmissionNumber = admissionNumber;
        PatientId = patientId;
        DepartmentId = departmentId;
        ConsultantId = consultantId;
        WardId = wardId;
        BedId = bedId;
        AdmissionDateTime = admissionDateTime;
        AdmissionType = admissionType;
        ReasonForAdmission = reasonForAdmission;
        Status = initialStatus;
    }

    public static Admission Create(
        string admissionNumber,
        Guid patientId,
        Guid departmentId,
        Guid consultantId,
        Guid wardId,
        Guid bedId,
        DateTime admissionDateTime,
        AdmissionType admissionType,
        string reasonForAdmission,
        Guid? createdBy)
    {
        Guard.AgainstNullOrWhiteSpace(admissionNumber, nameof(admissionNumber));
        Guard.AgainstNullOrWhiteSpace(reasonForAdmission, nameof(reasonForAdmission));

        return new Admission(
            Guid.CreateVersion7(),
            admissionNumber,
            patientId,
            departmentId,
            consultantId,
            wardId,
            bedId,
            admissionDateTime,
            admissionType,
            reasonForAdmission.Trim(),
            AdmissionStatus.Admitted,
            createdBy);
    }

    /// <summary>Raised from OPD before any ward/bed has been chosen — WardId/BedId stay null
    /// (AssignBed sets them once IPD picks a bed) and Status starts at Requested rather than
    /// Admitted. AdmissionNumber is still generated by the same
    /// IAdmissionIdentifierGenerator/service-layer convention Create's callers already use —
    /// this factory doesn't generate its own.</summary>
    public static Admission CreateRequest(
        string admissionNumber,
        Guid patientId,
        Guid departmentId,
        Guid consultantId,
        DateTime requestedDateTime,
        AdmissionType admissionType,
        string reasonForAdmission,
        Guid? createdBy)
    {
        Guard.AgainstNullOrWhiteSpace(admissionNumber, nameof(admissionNumber));
        Guard.AgainstNullOrWhiteSpace(reasonForAdmission, nameof(reasonForAdmission));

        return new Admission(
            Guid.CreateVersion7(),
            admissionNumber,
            patientId,
            departmentId,
            consultantId,
            null,
            null,
            requestedDateTime,
            admissionType,
            reasonForAdmission.Trim(),
            AdmissionStatus.Requested,
            createdBy);
    }

    public void Update(
        Guid departmentId,
        Guid consultantId,
        AdmissionType admissionType,
        string reasonForAdmission,
        Guid? updatedBy)
    {
        Guard.AgainstNullOrWhiteSpace(reasonForAdmission, nameof(reasonForAdmission));

        DepartmentId = departmentId;
        ConsultantId = consultantId;
        AdmissionType = admissionType;
        ReasonForAdmission = reasonForAdmission.Trim();
        MarkUpdated(updatedBy);
    }

    /// <summary>Caller (AdmissionService) is responsible for flipping the old/new beds'
    /// Available/Occupied status and for rejecting the call while not Admitted.</summary>
    public void TransferBed(Guid newWardId, Guid newBedId, Guid? updatedBy)
    {
        WardId = newWardId;
        BedId = newBedId;
        MarkUpdated(updatedBy);
    }

    /// <summary>Fulfils a Requested admission once IPD has picked a ward/bed — the other half
    /// of CreateRequest. Caller (AdmissionService) is responsible for the same Ward/Bed
    /// existence/availability checks CreateAsync already runs for a direct admission, plus the
    /// matching Bed.SetStatus(Occupied)/AdmissionBedStay.Create side effects.</summary>
    public void AssignBed(Guid wardId, Guid bedId, DateTime admissionDateTime, Guid? updatedBy)
    {
        if (Status != AdmissionStatus.Requested)
        {
            throw new InvalidOperationException($"Cannot assign a bed to an admission in status '{Status}' — only a Requested admission can be assigned one.");
        }

        WardId = wardId;
        BedId = bedId;
        AdmissionDateTime = admissionDateTime;
        Status = AdmissionStatus.Admitted;
        MarkUpdated(updatedBy);
    }

    /// <summary>Withdraws or declines a Requested admission before any bed was ever assigned —
    /// no bed side effects, since none were ever occupied.</summary>
    public void CancelRequest(Guid? updatedBy)
    {
        if (Status != AdmissionStatus.Requested)
        {
            throw new InvalidOperationException($"Cannot cancel an admission in status '{Status}' — only a Requested admission can be cancelled this way.");
        }

        Status = AdmissionStatus.Cancelled;
        MarkUpdated(updatedBy);
    }

    /// <summary>Caller (AdmissionService) is responsible for validating the discharge date
    /// against AdmissionDateTime and for freeing the bed.</summary>
    public void Discharge(
        DateTime dischargeDateTime,
        Contracts.DischargeType dischargeType,
        string? finalDiagnosis,
        string? dischargeNotes,
        string? followUpAdvice,
        Guid? updatedBy)
    {
        Status = AdmissionStatus.Discharged;
        DischargeDateTime = dischargeDateTime;
        DischargeType = dischargeType;
        FinalDiagnosis = finalDiagnosis;
        DischargeNotes = dischargeNotes;
        FollowUpAdvice = followUpAdvice;
        MarkUpdated(updatedBy);
    }

    /// <summary>Caller (IPDBillingService) is responsible for rejecting this call with a
    /// proper Result.Failure when not Discharged or when FinalInvoiceId is already set — see
    /// GenerateFinalBillAsync.</summary>
    public void SetFinalInvoiceId(Guid invoiceId, Guid? updatedBy)
    {
        FinalInvoiceId = invoiceId;
        MarkUpdated(updatedBy);
    }
}
