// <auto-generated />
using System;
using HMS.Modules.OpdConsultation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HMS.Database.Migrations.OpdConsultation.Migrations
{
    [DbContext(typeof(OpdConsultationDbContext))]
    partial class OpdConsultationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("opd_consultation")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HMS.Modules.OpdConsultation.Domain.OpdConsultationDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiagnosisId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosis_id");

                    b.Property<Guid>("OpdConsultationNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("opd_consultation_note_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_opd_consultation_diagnoses");

                    b.HasIndex("DiagnosisId")
                        .HasDatabaseName("ix_opd_consultation_diagnoses_diagnosis_id");

                    b.HasIndex("OpdConsultationNoteId")
                        .HasDatabaseName("ix_opd_consultation_diagnoses_note_id");

                    b.ToTable("opd_consultation_diagnoses", "opd_consultation");
                });

            modelBuilder.Entity("HMS.Modules.OpdConsultation.Domain.OpdConsultationInvestigation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OpdConsultationNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("opd_consultation_note_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.HasKey("Id")
                        .HasName("pk_opd_consultation_investigations");

                    b.HasIndex("OpdConsultationNoteId")
                        .HasDatabaseName("ix_opd_consultation_investigations_note_id");

                    b.ToTable("opd_consultation_investigations", "opd_consultation");
                });

            modelBuilder.Entity("HMS.Modules.OpdConsultation.Domain.OpdConsultationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<string>("ClinicalHistory")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("clinical_history");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("EmergencyReviewInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("emergency_review_instructions");

                    b.Property<string>("ExaminationFindings")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("examination_findings");

                    b.Property<string>("FollowUpInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("follow_up_instructions");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PlanOfManagement")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("plan_of_management");

                    b.Property<string>("PresentingComplaints")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("presenting_complaints");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("integer")
                        .HasColumnName("pulse_rate");

                    b.Property<Guid?>("ReferralConsultantId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_consultant_id");

                    b.Property<Guid?>("ReferralDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_department_id");

                    b.Property<string>("ReferralReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("referral_reason");

                    b.Property<DateOnly?>("ReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("review_date");

                    b.Property<int?>("SpO2Percent")
                        .HasColumnType("integer")
                        .HasColumnName("spo2_percent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TemperatureF")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_f");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_opd_consultation_notes");

                    b.HasIndex("ConsultationId")
                        .IsUnique()
                        .HasDatabaseName("ux_opd_consultation_notes_consultation_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_opd_consultation_notes_patient_id");

                    b.ToTable("opd_consultation_notes", "opd_consultation");
                });

            modelBuilder.Entity("HMS.Modules.OpdConsultation.Domain.OpdConsultationDiagnosis", b =>
                {
                    b.HasOne("HMS.Modules.OpdConsultation.Domain.OpdConsultationNote", null)
                        .WithMany("Diagnoses")
                        .HasForeignKey("OpdConsultationNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opd_consultation_diagnoses_note_id");
                });

            modelBuilder.Entity("HMS.Modules.OpdConsultation.Domain.OpdConsultationInvestigation", b =>
                {
                    b.HasOne("HMS.Modules.OpdConsultation.Domain.OpdConsultationNote", null)
                        .WithMany("Investigations")
                        .HasForeignKey("OpdConsultationNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opd_consultation_investigations_note_id");
                });

            modelBuilder.Entity("HMS.Modules.OpdConsultation.Domain.OpdConsultationNote", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("Investigations");
                });
#pragma warning restore 612, 618
        }
    }
}
